### ISSUE TITLE
Exhibitionバーチャルドローンの文章修正

### ISSUE THREAD

**Issue by asaga** [dojocon-japan/dojocon-japan.github.io#101]
文章を短くしてみましたので、こちらの内容に差し替えお願いします。

タイトル：
MR（混合現実）体験！Oculus Riftでバーチャルドローンを飛ばそう！

説明：
MRとは ＝ VR（バーチャルリアリティ）と現実との混合世界。 VRゴーグルから取り込まれた実風景に、CGのドローンをリアルタイム合成。VRゴーグルの中のバーチャルドローンをゲームパッドで操縦してみよう！（対象年齢：13歳以上）
（協力：株式会社XOOMS(ズームス））

**Comment by kozaru** [comment]
@asaga 追加したので、Closeします。

**Comment by asaga** [comment]
ありがとうございました。
