### ISSUE TITLE
「子供」に統一

### ISSUE THREAD

**Issue by tkc49** [dojocon-japan/dojocon-japan.github.io#104]
「子供」に統一でお願いします。
https://www.evernote.com/l/ABtGJ3v-k41I2oPFBrEd3hrFS8wpKNh7-tYB/image.png

**Comment by kozaru** [comment]
@tkc49 
念のための確認です。「子供」に統一は、公式サイトトップページのみですよね？

**Comment by kozaru** [comment]
@ixkaito ありがとうございました。

**Comment by tkc49** [comment]
ありがとうございます！
