### ISSUE TITLE
「プログラミング教育」に統一

### ISSUE THREAD

**Issue by tkc49** [dojocon-japan/dojocon-japan.github.io#105]
2カ所お願いしますm(_ _)m
https://www.evernote.com/l/ABv-aPs0jRxGy5660YA4zKLI_gmxXdQzTvwB/image.png

**Comment by ixkaito** [comment]
@tkc49 
ニュースにも2箇所あったので同じく修正しました。 See ff590c3

**Comment by ixkaito** [comment]
Fixed in 4ff46b5.
