### ISSUE TITLE
スポンサーロゴ

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#11]
ロゴ情報（正式名称・URL・ロゴを使用）
https://docs.google.com/spreadsheets/d/1EScDR67LrJGzcgGuVBLK7gfhdJzYB5pZeJe9a80vyKY/edit#gid=0

ティザーで使っていた加工済みデータはこちらにあります。
https://drive.google.com/drive/folders/0B9m59ut-K_FzUUlLRTNPNGZySGM

**Comment by okhiroyuki** [comment]
@kozaru @ixkaito 
さきほど、書籍スポンサーの翔泳社さんより、データを頂きました。
使えそうかどうかも含めて、一度確認ください。

**Comment by kozaru** [comment]
@ixkaito ロゴの情報不足している部分あればお知らせください。
[ティザーのデータ](https://drive.google.com/drive/folders/0B9m59ut-K_FzUUlLRTNPNGZySGM)
[元データ：リンクがあります](https://docs.google.com/spreadsheets/d/1EScDR67LrJGzcgGuVBLK7gfhdJzYB5pZeJe9a80vyKY/edit#gid=0)

### 掲載順

Gold 1
1. AMIMOTO AMI

Silver 4（掲載可能3）
1. （ロゴ未着のため、現状掲載不可）
2. 一般社団法人未踏
3. EC-CUBE （株式会社ロックオン）
4. 株式会社神戸デジタル・ラボ

Blonze 3
1. 株式会社TAM
2. アールスリーインスティテュート
3. Cafigla LLC.（合同会社カフィグラ）

**Comment by kozaru** [comment]
@okhiroyuki 画像見つけたのですが、加工済みの画像置き場なので、スポンサーの別フォルダに移動させました。確認するのでしばらくおまちください！

https://drive.google.com/drive/folders/0B9m59ut-K_FzdWc0Q2JTUHR0SEk

**Comment by okhiroyuki** [comment]
@kozaru ありがとうございます！

**Comment by kozaru** [comment]
@okhiroyuki イラレで開いたので、大丈夫です！

**Comment by kozaru** [comment]
@okhiroyuki 
#75 でマージされましたので、確認お願いします。

**Comment by kozaru** [comment]
@michieymt メンション忘れてた！ごめんなさい！
@okhiroyuki お二人どちらかで確認いただき、問題なければ、Closeお願いします。

**Comment by kozaru** [comment]
@michieymt 
画像のAltは、正式名称を使用したらよいですか？また、その場合（）で書かれているものも必要ですか？
ブラウザでは見えない部分ですが、それ以外に使用する場所もないので、念のため、ご確認をお願い致します。

**Comment by michieymt** [comment]
はい、正式名称でお願いします。
カッコも要ります。

よろしくお願いします！

**Comment by kozaru** [comment]
@michieymt  本日午後以降に修正しますね。
@ixkaito 上記連絡もれでした。すみません。後ほど、Wikiに記載しておきます。

**Comment by kozaru** [comment]
@michieymt 
@okhiroyuki 
公開まで分できたのでクローズします。
次回からは、追加時にIssueを立ててご依頼おねがいします。

**Comment by kozaru** [comment]
@michieymt 
サイト制作のWikiに正式名称の記載方法を追記しました。
https://megumilog.backlog.jp/wiki/DOJOCON/60_%E3%82%B5%E3%82%A4%E3%83%88%E5%88%B6%E4%BD%9C

**Comment by michieymt** [comment]
ありがとうございます: )
