### ISSUE TITLE
公開後のプレビューリポジトリと本番リポジトリのマージ

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#115]
技術的な方法はカイトさんに確認中です。

@ixkaito @Ippey 技術的なことではない部分での相談です。

例えば、
広報チーム・Webチーム双方ともプレビューリポジトリ・masterブランチにコミットマージ後、プレビューにて確認中の内容があり、どちらかがFixして、片方はペンディングの状態になった場合、

待てるのであれば、片方のFixを待てばいいと思うのですが、現時点ではその連絡方法や確認方法が決まっていません。

公開してよい情報がIssueで依頼されるはずなので、概ね大丈夫なのでは思っていますが、担当者間（カイトさん、一平さん、小寺）でその辺りの連携を考える必要がありますか？

考える必要があると思われる場合、どうしたらよいか、良き案あれば、ご提案ください。

**Comment by Ippey** [comment]
@ixkaito @kozaru 

ちがったらすいません。レポジトリの反映は、
1. localのマスターを最新状態にする（プレビュー -> local）
2. localで該当コンテンツ修正用ブランチを作成
3. プレビュー用レポジトリにプルリク（local -> プレビュー）
4. OKなら本番用レポジトリにプルリク（local -> 本番）

という流れで更新するというお話だったと思うので
上記問題には影響が出ない（片方fixで本番とマージしても問題ない）と
思っていました。

影響が出るようであれば、
例えば本番レポジトリへの反映は定期的なもの（例：毎週月曜にマージとか）とし、
当日マージ前に確認用issueを立てたりなどして、マージしても問題ないか確認を
とるとかどうでしょうか？

**Comment by kozaru** [comment]
@Ippey 
タイミングの問題かと。
レポジトリの反映はおっしゃているとおりです。
1. Aさんが12時にプレビュー（master）をプル後、
2. localの内容をプレビュー（master）にプルリクエスト&マージ
3. プレビューで担当者と確認中
4. Bさんが13時にプレビュー（master）をプル後、
5. localの内容をプレビュー（master）にプルリクエスト&マージ
6. 5はそのまま反映できるため、本番にマージ（※この時点でAさんのプレビュー内容は確認中）

Aさんが確認後プレビューを修正しようと思うと、公開されているという状態になってしまうなと。
毎週でもいいですが、そのタイミングでプレビュー内のものがすべて公開OKとは限らないですし、公開のタイミングを見る内容がある可能性もあります（7/11にEntry開始！等の掲載時間を決めて配信する記事など）

一人でやっているようなら、そのへんを調整は可能だと思うのですが、複数になるとルールが必要ですよねって話でした。わかりづらくてすみません。

**Comment by kozaru** [comment]
@ixkaito 
Issueに公開依頼がある内容は、すべて公開OKになったものとして、修正はタイポや写真加工位置の調整程度にしておけば、大丈夫かな？と思ってきました。いかがでしょうか？

@Ippey 
Newsは大勢の方が確認されるので、文面確認はプレビューがいいのかなと思っていますが、プレビュー以外での確認は可能ですか？

**Comment by ixkaito** [comment]
@kozaru @Ippey 
お待たせしました。デプロイ周りが完了しました。
公開の手順はとても簡単です。
今までどおり、master ブランチ上ですべての確認を完了させたあと、
release ブランチに対してプルリクを送ります (base: release/compare: master)。
このとき、基本的にすでに一度テストしているのですぐにマージできますので、
あとはマージすればしばらくしたら本番に反映されます。

**Comment by kozaru** [comment]
@ixkaito ありがとうございました！

**Comment by kozaru** [comment]
@ixkaito 
@Ippey 
1. それぞれのブランチ→masterにマージ ※
2. 担当者にプレビューOKかどうかの確認（必要な場合）
3. releaseにマージ

※ マージ後プレビューの確認が必要な場合は、マージコメントにその旨を記載（no-confirm とかでいいのでしょうか？かっこいいのがわからない...）して、担当でないコミットがmasterにあって、コミットした内容をそのまま公開可能な場合は、確認後マージしてください（merge with your commit みないな感じ？）でマージコメントを残してはいかがでしょうか？

また、確認が長引きそうなNews記事は、masterマージまでに別の箇所で確認するとかできるとなお良い気がします。

緊急時は、git flowっぽく、releaseからブランチ切って直接公開して、後ほどmasterにも反映させたら良いのではと思っています。

いかがでしょうか？

**Comment by kozaru** [comment]
@ixkaito 
メッセージは英語苦手なので、かっこいいの教えてもらえるとうれしいです。

**Comment by kozaru** [comment]
@Ippey 私が更新する範囲は、多分超急ぎとかあまりないと思うので、masterマージの際、releaseされていないNewsが残っていたら、Fixしたら一緒にマージお願いします！って連絡すると思います。

**Comment by kozaru** [comment]
<img width="1115" alt="2016-06-21 18 27 21" src="https://cloud.githubusercontent.com/assets/2457308/16224669/0047469c-37de-11e6-9e09-34a0f950d8a5.png">

こんなイメージです。
このやり方でなくても良いのですが、良い案がないので...あれば教えて下さいね。

**Comment by Ippey** [comment]
@ixkaito @kozaru 
了解です。ありがとうございます。
次のニュースから実施してみますー

**Comment by kozaru** [comment]
ではそうしましょう。Closeしますね。Issueに書いておきますね。
