### ISSUE TITLE
【スポンサーロゴ掲載の依頼】 ファーストサーバ株式会社

### ISSUE THREAD

**Issue by michieymt** [dojocon-japan/dojocon-japan.github.io#117]
ファーストサーバ株式会社

掲載情報
https://docs.google.com/spreadsheets/d/1EScDR67LrJGzcgGuVBLK7gfhdJzYB5pZeJe9a80vyKY/edit#gid=0

ロゴの置き場所
https://drive.google.com/drive/u/0/folders/0ByNa_SE0ubFuV21wSHFWc09lYW8

ブロンズの４番目です。

これで大丈夫でしょうか？
足りない情報がありましたらお知らせください。
よろしくお願いします。

**Comment by ixkaito** [comment]
@michieymt 
ありがとうございます！追加しました。

**Comment by michieymt** [comment]
@ixkaito 
ありがとうございます。お知らせします！
