### ISSUE TITLE
【ニュース】配布用バナー告知

### ISSUE THREAD

**Issue by Ippey** [dojocon-japan/dojocon-japan.github.io#118]
タイトル：
DojoCon Japan 2016のバナーをご用意しました！

公開日：
2016/6/20

草稿：
PRチームで作成します。

サムネイル画像：
後ほど連絡

**Comment by Ippey** [comment]
参考ページ：

https://2015.kansai.wordcamp.org/banner/

**Comment by Ippey** [comment]
@mayurin 
原稿作成しました。
TOP用の画像入稿次第、プレビュー用サイトにプルリクを送ります。

https://drive.google.com/open?id=1n5q_wCAGd9GZYf5u7UZrw0RaWjc-1hRixKQT2xqzTxA

**Comment by mayurin** [comment]
@Ippey https://drive.google.com/open?id=0B-O-Ui4qJxjLc3BpWktoSGdMbTQ
画像作りました。よろしくお願いします。

**Comment by kozaru** [comment]
@Ippey プルリクちょっとお待ち下さい。
@tkc49 この記事はご確認済みでしょうか？まだでしょうか？

**Comment by tkc49** [comment]
@kozaru 
@Ippey 
確認しましたー！
OKですー！

**Comment by ixkaito** [comment]
ソースコードのスタイルを追加 See: #128

**Comment by ixkaito** [comment]
外部からなので、ドメインが必要なので追加しました。 See 909ebae
