### ISSUE TITLE
【セッション】阿部さんセッション概要　追加

### ISSUE THREAD

**Issue by Ippey** [dojocon-japan/dojocon-japan.github.io#119]
以下の内容でお願いします。
タイトルが変わりましたので、タイムテーブルの部分も変更お願いします。
急ぎではないです。

【タイトル】
基調講演：「子供達にプログラミングをサポートする上で大事なポイント」

【概要】
最近の日本では子供のプログラミング教室が盛り上がりを見せていますが、阿部先生は10年以上前からプログラミング教育に貢献されています。また、CoderDojoに関しても日本初のDojoが開設された頃よりその活動を見守ってくださっています。阿部先生がどのようなきっかけでプログラミング教育に取り組まれるようになったのか、ほぼ全てのDojoで導入されているScratchが他の教育用言語と何が違うのか、先生のプログラミング教育への姿勢や現在行われている取り組みについて、そして子供にプログラミングを学ぶ機会を非営利で提供するCoderDojoのこれからに期待されることをお話しいただきます。

**Comment by kozaru** [comment]
@Ippey プレビューにマージしています。

**Comment by Ippey** [comment]
確認しました。OKです。
本番レポジトリへのマージをお願いします。
