### ISSUE TITLE
jpegtran-binについて

### ISSUE THREAD

**Issue by Ippey** [dojocon-japan/dojocon-japan.github.io#120]
前に、assets/_imagesに画像を置いてもコピーできないという問題が起きた件ですが
jpegtran-binが入っていないのが原因でした。

`
npm install --save jpegtran-bin
`

を実行して、`npm start`すると画像がコピーされました。
上記コマンド実行によりpackage.jsonのdependenciesが

```
  "dependencies": {
    "jpegtran-bin": "^3.0.6",
    "jquery": "^2.2.4"
  }

```

となりますが、
これのプルリクを送ったほうがよいでしょうか？

**Comment by kozaru** [comment]
@Ippey @ixkaito 小寺のPCでは動いていました。npmでやっていないからも。（npmでインストールされているものは動かしていますが、gulpコマンド経由で作業しています）

なので、お二人で決めてくださればと思います！よろしくお願いいたします。

**Comment by ixkaito** [comment]
@Ippey 

> assets/_imagesに画像を置いてもコピーできない

というのはどこかに issue 上がってますか？具体的にどのような症状ですか？
ちなみに、`jpegtran-bin` は `imagemin` の dependency なので、`package.json` に書かなくてもインストールされるはずです。`npm install` 失敗してるかもしれません。

@kozaru 
`npm start` は `gulp` を実行してるだけなので、同じものです。

**Comment by Ippey** [comment]
@ixkaito 
issueはあげてないです。前にニュースの画像の置き場所の話をしていた時に
_imagesに画像をおけば勝手にコピーしてくれるということだったので
やってみたらlocalで動作しなかったので、ちょっと昨日調べていました。

npm startした際に

```
spawn node_modules/jpegtran-bin/vendor/jpegtran ENOENT
```

こんな感じのエラーが出てたので
node_modulesのディレクトリを調べてみてjpegtran-binが入っていなかったので
インストールしました。
imageminのdependenciesなら、たしかにpackage.jsonに書かなくても入るので
インストール時に何かあって失敗してたのかもしれないです。

**Comment by ixkaito** [comment]
@Ippey 
そうだったんですね。やはり `npm install` の失敗っぽいですね。こちらでは普通に `jpegtran-bin` は `node_modules` に入ってますね。他に考えられるのは Node.js のバージョンの違いとかですかね。

ではとりあえず close しますね。
