### ISSUE TITLE
OGP差し替えお願いします。

### ISSUE THREAD

**Issue by mayurin** [dojocon-japan/dojocon-japan.github.io#121]
https://drive.google.com/open?id=0B-O-Ui4qJxjLUnppbkVMMC1FTGs
すみません、1200×630が推奨サイズみたいなので、作りなおしました。
こちらに差し替えをお願いいたします。

**Comment by mayurin** [comment]
@ixkaito @kozaru もうちょっと練り直してますので、もう暫くお待ち下さい

**Comment by mayurin** [comment]
@ixkaito @kozaru すみません、調整終わりました。
こちらを差し替えお願いいたします。
https://drive.google.com/open?id=0B-O-Ui4qJxjLdjhsd1RoWVFMcDA

**Comment by kozaru** [comment]
@mayurin マージ方法等確認中なので、今しばらくお待ち下さいませ。

**Comment by kozaru** [comment]
@mayurin ogp前はjpegでしたが、今回はpngでよいですか？

**Comment by mayurin** [comment]
@kozaru はい、pngがよいと思います。ありがとうございます。

**Comment by kozaru** [comment]
@mayurin 了解です！

**Comment by kozaru** [comment]
@ixkaito プレビューに反映させています。jpegからpngに変わっています。jpegも残しています。

**Comment by ixkaito** [comment]
本番に反映されていますので close します
