### ISSUE TITLE
Twitterカードについて

### ISSUE THREAD

**Issue by mayurin** [dojocon-japan/dojocon-japan.github.io#122]
https://dev.twitter.com/ja/cards/overview
Twitterもアイキャッチ表示されないかな、と思っていたらFacebookのOGPみたいなTwitterカードというものがあるようです。
こちら私知らなかったのですが、これを設定することは可能でしょうか。
それとも認識間違いでしたらすみません。

**Comment by Ippey** [comment]
すでに入っているようです。

```

<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="DojoCon Japan 2016 - The more dojos, the more cool coders. -">
<meta name="twitter:image" content="http://dojocon.coderdojo.jp/assets/images/ogp.jpg">

```

**Comment by kozaru** [comment]
Card validatorでエラーが出ているようです。しばらくお待ち下さい。

**Comment by kozaru** [comment]
@mayurin マージ方法等確認中なので、今しばらくお待ち下さいませ。

**Comment by mayurin** [comment]
ありがとうございます！

**Comment by kozaru** [comment]
@ixkaito 少しだけ調べたので書いておきます。プレビューのURLで作業して、なにか残っても困るので、作業していません。

Card validatorでエラーが出ていました。
https://cards-dev.twitter.com/validator

OGPはプレビュー分は差し替えました。#125

OGP画像が大きいので、[Summary Card with Large Image](https://dev.twitter.com/cards/types/summary-large-image)にして、twitter:site が requiredになっているので、DojoConの username（@DojoConJapan ）を入れたほうが良いのかもしれません。また、validate も DojoConのアカウントでやったほうが良いような気はしています。

Wikiをみましたが、アカウント情報はありませんでした。
よろしくお願いいたします。

**Comment by ixkaito** [comment]
Fixed in 2560711
