### ISSUE TITLE
スピーカーポップアップ：SNS以外へのリンク

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#13]
URLへのリンク依頼がありました。
アイコン他、どうしましょうか？

**Comment by kozaru** [comment]
アイルランドの方の分です。

**Comment by ixkaito** [comment]
@kozaru 
この issue の意味がちょっとよくわからないんですが、どこのことですか？
ちなみにスポンサーはポップアップではなく、通常のリンクの予定でした。

**Comment by kozaru** [comment]
@ixkaito タイトル間違ってました。スピーカーです。
スピーカーの方でFacebook/Twitterではなく、URLへのリンクの方がいらっしゃいました。
URL用のアイコンがほしいです。

**Comment by ixkaito** [comment]
@kozaru なるほど、作成します。多分日曜日以降になります。

**Comment by kozaru** [comment]
@ixkaito URL追加できました。ありがとうございました。
