### ISSUE TITLE
Newsコンテンツの公開前確認方法

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#132]
Newsコンテンツの公開前の確認を
@tkc49 にやっていただけることになりました。

それに伴い、Gitの流れを含めた公開までの確認方法を決めたいです。

**Comment by kozaru** [comment]
@Ippey @tkc49 
プレビューで確認がよいですか？

**Comment by Ippey** [comment]
ニュースは広報が作成しますが、依頼は各チームから上がるので
各チームに確認してもらうためにもプレビューレポジトリでの確認が望ましいです。

**Comment by kozaru** [comment]
@Ippey 承知しました！

@ixkaito 上記を踏まえた、今回用のGitFlow的なものが必要かもしれません。良き案あれば、教えていただきたいです。

**Comment by tkc49** [comment]
@kozaru 確認しました。色々手順を検討して頂きありがとうございますm(_ _)m
WEBチームは人数が少ないので、無理のない運用でお願いします。
出来れば各チームのリーダーに作業が分散できると良いのですが・・・
このあたりは知識があまりないので、 @ixkaito @kozaru さんにお任せ致しますm(_ _)m

**Comment by kozaru** [comment]
@tkc49 #115で プレビューで確認に決定しました。

@Ippey 
@ixkaito Newsはmasterマージ後、すぐに公開ではなく、確認後releaseにマージという流れでお願い致します。

Closeします。
