### ISSUE TITLE
News：画像リンクとHTML表記の方法確認

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#134]
@ixkaito 
本番サイトはhttpアクセスだったと思っています。
そうである前提で、下記の対応でよいか確認お願いします。
#133 でプレビューにマージ分です。

@Ippey より
プルリク送りました。現象はhttpでアクセスしたときのみ起こります。（＝httpsでのアクセスであれば画像表示されました。）
原因としては、site.urlがhttpsなので、画像にsite.urlをつけると、画像のパスがhttpsスタートとなって正しく表示されないようになります。
対処としては、画像はsite.urlをprependしないようにしました。
コピペで貼る用のソースコードはsite.urlをprependしています。

**Comment by ixkaito** [comment]
@kozaru @Ippey 
#133 にもコメントしましたが、これで問題ございません。ありがとうございます。
