### ISSUE TITLE
TimeTable WorkShop ポップアップの挙動

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#14]
3b5ede6
上記のコミットを見てください。

ワークショップでEntryがあるのは、2つで、同じワークショップを数回行う予定です。
ポップアップを開いて、左右に移動すると、繰り返して、各ワークショップが表示されます。
多分、TimeTableからリンクがある分すべて、ループしているのだと思います。

**Comment by ixkaito** [comment]
それぞれ1回で済むようにできるとは思いますが、時間がかかりそうなので後回しで。

**Comment by kozaru** [comment]
ありがとうございました！
