### ISSUE TITLE
検索結果URLがhttpsになる問題を解決する

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#146]
Googleの検索結果で、公式サイトのURLが https になっています。
上記を解決するためのIssueです。

**Comment by kozaru** [comment]
Slackで上がっていた内容を書いておきますので、みなさまよろしくお願いいたします。（違っていたら直してください）
- リダイレクト処理が可能かどうか
- GoogleのURLへの優先度（https>http）
- [カスタムドメインのGitHubページでHTTPSを使う：Qiita](http://qiita.com/superbrothers/items/95e5723e9bd320094537)

DNS周りが関連する可能性があるので、
@yasulab にも 参加頂く予定です。（invite メール 送付済み）

**Comment by ixkaito** [comment]
まだ検索結果 HTTPS になってます？僕は普通に HTTP ですが。

**Comment by kozaru** [comment]
先ほど検索したらhttpでした。

**Comment by kozaru** [comment]
@Ippey @tkc49 いかがでしょうか？

**Comment by tkc49** [comment]
@kozaru @ixkaito 
あれ、httpになってますねー

**Comment by ixkaito** [comment]
close?

**Comment by tkc49** [comment]
Yes!
