### ISSUE TITLE
【セッション】谷岡さん

### ISSUE THREAD

**Issue by Ippey** [dojocon-japan/dojocon-japan.github.io#147]
写真をもらいなおしましたので
掲載をお願いします。

・スピーカー情報
・セッション（有償と無償で何が違う？
プログラミング教室/コミュニティー運営座談会）

**Comment by kozaru** [comment]
@akari-doi 
写真の加工お願いします！スプレッドシート追加済みです。

**Comment by akari-doi** [comment]
@kozaru こちらも完了しました！

**Comment by kozaru** [comment]
@Ippey 谷岡さんの（TENTOフェロー）の入り具合、プレビューで確認おねがいしたいです。

@akari-doi ありがとうございました！

**Comment by Ippey** [comment]
@kozaru OKです。本番へマージお願いします。

@akari-doi ありがとうございました！

**Comment by kozaru** [comment]
@Ippey 追加しましたのでCloseします。ご確認ありがとうございました！
