### ISSUE TITLE
【セッション】橋爪さん

### ISSUE THREAD

**Issue by Ippey** [dojocon-japan/dojocon-japan.github.io#148]
プロフィールが揃いましたので
掲載お願いします。

・プロフィール
・セッション情報（有償と無償で何が違う？
プログラミング教室/コミュニティー運営座談会）

**Comment by kozaru** [comment]
@akari-doi 
写真の加工お願いします！スプレッドシート追加済みです。

**Comment by akari-doi** [comment]
@kozaru 完了しました！

**Comment by kozaru** [comment]
@akari-doi ありがとうございました。

@Ippey こちらは確認はないので、#147確定後公開予定です。

**Comment by Ippey** [comment]
@kozaru @akari-doi ありがとうございました！

**Comment by kozaru** [comment]
@Ippey 追加したのでCloseします。
