### ISSUE TITLE
開催概要にCoderDojo Foundation後援情報を追記

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#149]
掲載するのであれば、開催概要の箇所だと思います。
後援： CoderDojo Foundation（ハイパーリンク先はhttps://coderdojo.com/about/coderdojo-foundation/）

**Comment by kozaru** [comment]
@tkc49 
@pictron 
@Ippey 
どなたに確認がいいかわからなかったのですが

開催日 : 2016年8月27日（土）
時間 : 10:30-16:30（開場 10:00）
場所 : 内田洋行 大阪 ユビキタス協創広場 CANVAS
参加費 : 無料
後援： CoderDojo Foundation

掲載順指定有りますか？

**Comment by tkc49** [comment]
@kozaru テキストの掲載順はそれで良いと思いますー！
これサイトにFoundationのバナー張らないとって思いました。

**Comment by kozaru** [comment]
@tkc49 上記とは別にって感じですか？

**Comment by kozaru** [comment]
@tkc49 上記で掲載しておきますね。バナーはチケットで話しましょう！

**Comment by kozaru** [comment]
@tkc49 とりあえず、テキストリンクを入れました。
バナーはBacklogで検討中です。
#147 確認後公開予定です。

**Comment by kozaru** [comment]
@tkc49 追加したのでCloseします。バナーはチケットで決まり次第Issueあげます。
