### ISSUE TITLE
Exhibition height

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#15]
073612b

上記のコミットでご確認ください。

文章量がマチマチのため、高さが統一されません。
jquery.matchHeight.jsのように揃うのなら、揃った方がよいかと思います。

**Comment by ixkaito** [comment]
結局4つなんですかね？

**Comment by kozaru** [comment]
まだ増えます。

**Comment by kozaru** [comment]
要検討の企画が３つあります。
https://docs.google.com/spreadsheets/d/11RX6rN3Xb4A889xnwHK97OHH_Pwg62Jjwmb2TzjeT6M/edit#gid=0

**Comment by ixkaito** [comment]
@kozaru なるほど。少し手間ですが、掲載数によって、都度レイアウトを調整した方がいいでしょうね。これだけなら CSS でいいかなと思います。JS にするにしても、プラグインは使わず、普通に書いても数行です。

**Comment by kozaru** [comment]
@ixkaito 作業日曜でよけれが、上記で対応します。お急ぎの場合、よろしくお願いします。

**Comment by kozaru** [comment]
@ixkaito 
プルリク出しています。
