### ISSUE TITLE
【セッション】岡田さん

### ISSUE THREAD

**Issue by Ippey** [dojocon-japan/dojocon-japan.github.io#152]
セッション概要の追加をお願いします。
急ぎではないのでカイトさんがウィーンから帰ってきてからでも大丈夫です。

セッション概要：
CoderDojo西宮・梅田では、昨年よりArduinoを使った電子工作をサポートしています。サポートを行うにあたっては、子供たちでもプログラミングができるように、Scratchのようなブロックを操作することでプログラミングできるツール「BlocklyDuino」を採用しています。
本ツールは、CoderDojoでの経験をもとに独自に作成したものであり、現在はWeb版とChromeApp版を無償公開しています。
本セッションでは、「BlocklyDuino」の具体的な使い方のほか、CoderDojo西宮・梅田での活用事例なども合わせて紹介いたします。

**Comment by kozaru** [comment]
@Ippey 上記プレビューでの確認必要ですか？

**Comment by kozaru** [comment]
プレビューで一旦確認おねがいします。

**Comment by kozaru** [comment]
@Ippey プレビューで確認後お知らせください。

**Comment by kozaru** [comment]
確認が週明けになりそうということでした。（メモ）

**Comment by Ippey** [comment]
確認しました。okですー

**Comment by kozaru** [comment]
ありがとうございました。マージしましたのでCloseします。

@ixkaito masterブランチ releaseにマージしました。（devが進んでいたので）
