### ISSUE TITLE
【セッション】チャンピオンパネルディスカッション

### ISSUE THREAD

**Issue by Ippey** [dojocon-japan/dojocon-japan.github.io#153]
セッション概要の追加をお願いします。
急ぎではないのでカイトさんがウィーンから帰ってきてからでも大丈夫です。

セッション概要：
文部科学省から発表された『2020年から小学校のプログラミング必修化』を受け、各地でプログラミング教室が設立されています。
CoderDojoのような無料のプログラミング教室と何がちがうのか、プログラミング必修化を受けて、今後どのように活動していくかなどを
有償プログラミング教室からTENTO　谷岡様、CoderDojoから橋爪さんにお話をうかがいます。

**Comment by kozaru** [comment]
@Ippey 表題と文章が違う気がするのですが...いかがでしょうか？
また、プレビューでの確認は必要ですか？

**Comment by kozaru** [comment]
お返事いただいてから、作業しますね。

**Comment by tkc49** [comment]
これ、無料と有償のセッションのやつですねー。

**Comment by Ippey** [comment]
あ、ごめんなさい。有償無償のやつです。

**Comment by kozaru** [comment]
有償、無償のセッションは、#87で公開されています。
このチケットが、そのセッション用なら、Closeしてもらえたらと思います。

**Comment by Ippey** [comment]
一旦出しなおします。
