### ISSUE TITLE
【スポンサーロゴ掲載の依頼】株式会社アーテック

### ISSUE THREAD

**Issue by michieymt** [dojocon-japan/dojocon-japan.github.io#154]
株式会社アーテック

シルバーの5番目です

https://docs.google.com/spreadsheets/d/1EScDR67LrJGzcgGuVBLK7gfhdJzYB5pZeJe9a80vyKY/edit#gid=0

よろしくお願いします。

**Comment by ixkaito** [comment]
@michieymt 
シルバー現在3つしかありませんが、4番目ということですか？

**Comment by michieymt** [comment]
@ixkaito 
そうですね、すみません。
一番目の企業からまだデータがきてないので
現在は4番目にしてください。

**Comment by ixkaito** [comment]
@michieymt 
そういうことですね、了解です。

**Comment by ixkaito** [comment]
Resolved in dda7ed8
