### ISSUE TITLE
【スポンサーロゴ掲載の依頼】株式会社シェアウィズ

### ISSUE THREAD

**Issue by michieymt** [dojocon-japan/dojocon-japan.github.io#155]
株式会社シェアウィズ

ブロンズの5番目です

https://docs.google.com/spreadsheets/d/1EScDR67LrJGzcgGuVBLK7gfhdJzYB5pZeJe9a80vyKY/edit#gid=0

よろしくお願いします。

**Comment by michieymt** [comment]
株式会社シェアウィズさんは
リンク先について注意書きがありますので、どうぞよろしくお願いします。

わからないことがあればお知らせくださいね。
@ixkaito

**Comment by ixkaito** [comment]
Resolved in 4949370
