### ISSUE TITLE
【スポンサーロゴ掲載の依頼】株式会社ドットインストール

### ISSUE THREAD

**Issue by michieymt** [dojocon-japan/dojocon-japan.github.io#156]
株式会社ドットインストール

ブロンズの6番目です

https://docs.google.com/spreadsheets/d/1EScDR67LrJGzcgGuVBLK7gfhdJzYB5pZeJe9a80vyKY/edit#gid=0

よろしくお願いします。

**Comment by ixkaito** [comment]
Resolved in a88be76
