### ISSUE TITLE
TestのError確認

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#159]
プルリクエストをマージする時点では、画面上ではテストOKになっていたのでマージしました。

ですが、#158 でテストエラーがでていました。

コメント見たのですが、よくわからなかったので連絡しました。もし問題あるエラーでしたらおしらせください。
そうでなければ、Closeしてください。

**Comment by ixkaito** [comment]
Travis CI 側のエラーっぽいので大丈夫です。

**Comment by kozaru** [comment]
ありがとうございました！
