### ISSUE TITLE
書籍&ツールスポンサーの掲載とスポンサー数の変更（公開後に追加）

### ISSUE THREAD

**Issue by okhiroyuki** [dojocon-japan/dojocon-japan.github.io#16]
修正箇所：
スポンサーロゴ掲示部分

修正内容：
下記、追加していただくことになると思います。
具体的な変更時期はロゴが揃ってからだとは思いますが、一応今のうちから挙げておきます。
- シルバースポンサーが現状で５つとなっております。（もう一枠増えるかもです）
- 書籍スポンサーが１つはいってます（翔泳社さん）
- ツールスポンサー（RALLYさんがたしか入ってたはず）

**Comment by asaga** [comment]
ツールスポンサーの件ですが、こちらから声かけて協力頂いているところはここに該当すると思って良いですよね。
VRやってもらうXOOMSさんとか。

**Comment by okhiroyuki** [comment]
そうですね。
なお、スポンサーもそうですが、掲載には下記のものが必要になるかと思います。
- ロゴ
- 正式な会社名
- URL

**Comment by kozaru** [comment]
@okhiroyuki この件、公式サイトオープン後に検討でよいのでしょうか？

@ixkaito オープン前に検討であれば、項目が追加されるので、必要であれば、デザインチームも入ってもらったほうがよいとおもいます。

**Comment by okhiroyuki** [comment]
@kozaru 
はい、これまだすぐにデータが揃ってこないと思います。

なお、たしかですが、 @ixkaito さんからは項目の追加は足す形でいけるんじゃないかとのお話をいただいた記憶があります。

**Comment by kozaru** [comment]
@okhiroyuki 了解です！
@ixkaito ということみたいなので、追加の際、おねがいしてもよいでしょうか？

**Comment by kozaru** [comment]
@okhiroyuki
#11の書籍スポンサーさん、公開時に載せますか？その他のツールスポンサーさんとの兼ね合いなど、も合わせて、ある程度まとまっての予定でしょうか？企画周りのツールスポンサーさんは @asaga どんな感じでしょうか？

**Comment by okhiroyuki** [comment]
書籍スポンサーとツールスポンサーを混ぜて、何かしらのカテゴリーを設けるなら、企画側と連動したほうがよさそうです。
今って、どんな区分でしょうか？

**Comment by kozaru** [comment]
Gold/Siver/Blonze + ここにツールスポンサー・書籍スポンサーとして入るのではと思っていますが、名称等も決まっていません。要相談ですね。これチケットに戻って、掲載内容が決まってからIssueにしたほうがよいかもです。

**Comment by okhiroyuki** [comment]
そうですね。
どのようなカテゴリーを設けるかは、ちょっと整理したほうがよいかと思いました。

ちなみに、通常のスポンサー枠以外に下記のようなものがありました。
- MakerFaire：Media & Community Sponsors
- wordcamp：Tool Sponsor

これを見る限り、Book と Tool でもいいような気がします。わかりやすいですから。
一般のかたがすぐ理解できるカテゴリーがいいですね。

**Comment by kozaru** [comment]
Book & Tool Sponsors（Books & Tools Sponsors）
または
Book & Tool（Books & Tools）
sいらない？ちょっとむずかしいですね。これで決まりなら、英語表記も確認が必要ですね。

**Comment by asaga** [comment]
企画関連だと、
・株式会社ズームス（バーチャルドローン）
・コモジラ研究所
・株式会社フェイスクリエイツ（RALLY）
がツール提供となります。

**Comment by kozaru** [comment]
名称（英語表記も含め、確認が必要）

Book & Tool Sponsors（Books & Tools Sponsors）
または
Book & Tool（Books & Tools）

掲載予定スポンサー
- 翔泳社
- 株式会社ズームス（バーチャルドローン）
- コモジラ研究所
- 株式会社フェイスクリエイツ（RALLY）

でよいでしょうか？上記のロゴ、正式名称（掲載用・画像のALTに入れます）、URLを下記のスプレッドシートに入れてもらっていいですか？
https://docs.google.com/spreadsheets/d/1EScDR67LrJGzcgGuVBLK7gfhdJzYB5pZeJe9a80vyKY/edit

@okhiroyuki 
@michieymt にお願いした方がいいですか？

**Comment by michieymt** [comment]
データと情報をざっくり送っていただけたら、私の方で準備しますよ？
ロゴの場所や依頼のスプレットシートは以前の通りで良いのですよね？

**Comment by kozaru** [comment]
@michieymt はい、情報の収集方法は、以前の通りでお願いします。
掲載名称は、検討中ですので、分かる形で区分を入れていただければと思います。

**Comment by michieymt** [comment]
では企業様から情報をいただいたら、メールを転送していただけたら小寺さんに依頼します。
情報の催促メールも必要でしたらやりますので、お知らせください。 @kozaru @asaga @okhiroyuki

**Comment by kozaru** [comment]
英語表記については、以下のチケットで確認中です。
https://megumilog.backlog.jp/view/DOJOCON-446

**Comment by kozaru** [comment]
@okhiroyuki 
@asaga 
こちら公式サイト公開時点に掲載しますか？のちほどでよいですか？
情報が揃っていないので、のちほどまとめてでもよいかなぁと思っていますが、いかがでしょうか？
（重要度合がわかっていないので、お二方できめていただければ助かります）

**Comment by asaga** [comment]
@kozaru @okhiroyuki 

これでサイト公開が遅れるのであれば、後からでも良いかなと思ってます。

**Comment by kozaru** [comment]
@asaga 
@okhiroyuki 
では、公式サイト公開後で進めたいと思います。
情報収集など、引き続きどうぞよろしくお願いいたします。

**Comment by kozaru** [comment]
@okhiroyuki 
@asaga 
書籍&ツールスポンサーのタイトルは、In-Kind Sponsor でよいですか？
https://megumilog.backlog.jp/view/DOJOCON-446

**Comment by kozaru** [comment]
@pictron 
書籍&ツールスポンサーのロゴを公式サイトに公開することになっています（前回のMTGで決まったと思います。そのあたり、ちょっと不確かです。必要でしたら、議事録確認していただきたいです）

英語表記を、下記のチケットで相談後、In-Kind Sponsor にしたいと思っています。
ご確認お願いします。
https://megumilog.backlog.jp/view/DOJOCON-446

**Comment by kozaru** [comment]
まだみなさんにはアナウンスしていませんが、今後Issueで依頼していただくもの（Newsを除く）は、公開OKのものにしていただこうと思っています。スポンサーの掲載依頼は、@michieymt → @ixkaito なので、

@okhiroyuki @asaga @pictron 
書籍&ツールスポンサー（In-Kind Sponsor）、詳細決まって、掲載OKになったら、@michieymt に連絡おねがいしますね。

@michieymt 
依頼については、このIssueでやっていただいてもいいと思いますし、個別にIssueを立てたほうがよいようでしたら、詳細決定後、こちらをCloseしていただいて、依頼用のIssueを立てていただければと思います。

よろしくお願いいたします。

**Comment by michieymt** [comment]
@kozaru
はい、了解です。

**Comment by asaga** [comment]
@okhiroyuki 名称についてはスポンサーチームで決めて頂ければと思います。（個人的にはOKだと思いますが）

**Comment by okhiroyuki** [comment]
はい、Backlogで最終確認とります。
https://megumilog.backlog.jp/view/DOJOCON-446

**Comment by okhiroyuki** [comment]
@asaga @kozaru 
細谷さんから、OKにでたので、**In-Kind Sponsor**で行きましょう！

**Comment by kozaru** [comment]
@okhiroyuki 
@asaga ありがとうございました！
では、更新の際は、今までのスポンサーのご依頼の流れに合わせて、
@michieymt にご連絡をお願い致します。

@ixkaito 
書籍＆ツールスポンサー「In-Kind Sponsor（or In-Kind Sponsors）」に決まりました。
@michieymt から、更新依頼が来たらよろしくお願い致します。

@michieymt 
ご存知かもですが、書籍スポンサーさんの情報を以前
@okhiroyuki からいただいたのですが、場所を見失ってしまいました。
掲載順等決まって、こちらにご依頼までにご確認お願いできないでしょうか？
たしか、.psファイルか何かで、加工可能かどうかのご依頼時にみたような気がします。
その際、Ai or Ps で開いたので大丈夫ですーとお返事しています。

**Comment by okhiroyuki** [comment]
@ixkaito @kozaru
In-Kind Sponsorの準備が整ったところから、掲載をお願いいたします。
issueは別途立てております。
今のところ、掲載数は7社です。
たぶん、これ以上は増えないとは思います...

あと、このissueは閉じてもよいと思います。

**Comment by kozaru** [comment]
@okhiroyuki 承知しました！
@ixkaito 確認後closeお願い致します。
