### ISSUE TITLE
【スピーカー】谷岡さんの掲載場所を変更

### ISSUE THREAD

**Issue by Ippey** [dojocon-japan/dojocon-japan.github.io#165]
掲載順を変更することになりましたので、
谷岡さんを東さんの後ろに変更お願いします。

**Comment by kozaru** [comment]
@Ippey プレビューを修正しました。
ご確認お願いいたします。

追伸：確認不要の時は、ご依頼時に書いていただければ、公開後お知らせいたします。

**Comment by Ippey** [comment]
@kozaru OKです。
公開お願いします。

**Comment by kozaru** [comment]
@Ippey 公開しました。Closeします。
