### ISSUE TITLE
Staff アイコン+テキストから 各URLへリンク

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#17]
bbbba2b

上記のコミットでStaffのテキストを入れました。
URLを頂いている方には、リンクを入れたいです。

**Comment by kozaru** [comment]
@ixkaito 
リンク追加後、Slackで皆さんへの確認を取りたいです。

リンクの追加は作業しますので、リンクサンプルもしくはリンクの付け方（aタグでOKなど）、お知らせください。

**Comment by ixkaito** [comment]
テキストって例えばどういうのですか？

**Comment by kozaru** [comment]
すみません、この件、aタグいれたら解決できたので、closeします。
