### ISSUE TITLE
【レイアウト依頼】WorkShop ポップアップ内イメージを配置（+ Facilitator )

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#170]
@ixkaito Workshopのポップアップ内に写真を掲載したいという依頼がきました。
お願いできますか？お忙しいようなら、レイアウトします。
- 写真はサイズを指定してほしい
- Facilitatorも入るかも（名前のみの予定）

---

> > セッションの場合はスピーカーの写真を掲載していますが、ワークショップの場合も同様に写真を載せる事は可能でしょうか？
> > スピーカー写真よりサイズ大き目になるかなとは思いますが、掲載が可能であればサイズもご指定頂けるとありがたいです。
> 
> というご質問があります。
> エキシビションと同じようなサイズ感、ノーマスクの写真をモーダルウィンドウ上に載せれたらいいかなと思います。が可能でしょうか。
> 
> タイトル
> 開催時間
> (Facilitatorがもしかしたら入るかも)
> テキスト
> ワークショップのイメージ写真（右寄せ）

---

via slack #web
[Backlog Ticket Comment](https://megumilog.backlog.jp/view/DOJOCON-471#comment-1143693032)

**Comment by ixkaito** [comment]
@mayurin @kozaru 
大丈夫ですよ。一枚のみ？複数枚想定？

**Comment by kozaru** [comment]
@ixkaito ありがとうございます！おそらく1枚かと思いますが、
@mayurin 複数になる可能性あるかしら？
