### ISSUE TITLE
Faavoと毎日新聞の記事の外部リンクをtarget=_blankに

### ISSUE THREAD

**Issue by tkc49** [dojocon-japan/dojocon-japan.github.io#174]
タイトル属性がない？
https://www.evernote.com/l/ABsQ9iOLbSlP45Yews4Vun0SC8BZdo1WHrQB/image.png

あと、外部サイトなので、target=_blankが良いかなと思いました！

**Comment by kozaru** [comment]
何もしてないのにreleaseにマージしたら、closeされましたが、反映されていないので調査中です。

**Comment by kozaru** [comment]
@tkc49 上記修正しました！

**Comment by tkc49** [comment]
@kozaru 確認しました！ありがとうございます！！！

**Comment by ixkaito** [comment]
@kozaru コミットメッセージに fix, resolve, close のあとに issue ナンバー入れると、master にマージされたタイミングで自動 close されます。

**Comment by kozaru** [comment]
@ixkaito 知らなかったです。覚えておきます！ありがとうございました！
