### ISSUE TITLE
Favvoのサムネイルの高さがちょっとずれているので差し替えお願いします。

### ISSUE THREAD

**Issue by mayurin** [dojocon-japan/dojocon-japan.github.io#175]
Favvoのサムネイルの高さがちょっとずれているので下記データと差し替えお願いします。
https://drive.google.com/open?id=0B-O-Ui4qJxjLYkxmeEl2UXRzUXc
 NEWSのサムネイルは
width/6 : height/4の比率で統一が良いかと思います。

**Comment by kozaru** [comment]
何もしてないのにreleaseにマージしたら、closeされましたが、反映されていないので調査中です。

**Comment by kozaru** [comment]
@mayurin @Ippey 上記修正しました！
