### ISSUE TITLE
Workshopの説明文掲載

### ISSUE THREAD

**Issue by asaga** [dojocon-japan/dojocon-japan.github.io#181]
Coming soon...になっている部分の更新をお願いします。
説明文の行が多すぎますかね？

■タイトル
Scratchって何？ 初めてのCoderDojo! −オトナもコドモもニンジャになろう−

■説明文
CoderDojoに参加する子供達のことをNinja（ニンジャ）と呼びます。本来Dojoは小学生〜高校生くらいまでの子供達のための場所ですが、このワークショップでは特別に大人にもニンジャになってもらい、子供達と一緒にDojoを体験していただきます。内容は初めてScratchに触る子供達を対象とした簡単なプログラミング講座です。何が出来るかな？子供は楽しく！大人は忘れた子供心を取り戻そう！

　注意事項：
　・本ワークショップは事前のお申し込みが必要です。
　・大人だけ、子供だけでも参加可能です。
　・各回大人６名、子供６名。
　・PCを持参頂く必要があります。
　・詳細はお申し込みページをご覧下さい。（お申し込みページは7/11開設予定です）

説明文に掲載する写真はチラシで使ってる素材を頂きたいです。＞ @akari-doi さん

時間が50分から90分に変更になったので、タイムテーブルの枠も変更をお願いします。
　１回目：10:40 - 12:10
　２回目：12:30 - 14:00
　３回目：14:20 - 15:50

**Comment by akari-doi** [comment]
素材写真かしこまりました。
@kozaru @ixkaito 確かここはまゆりんがデザインはwebチームおまかせでと言ってたところだと思うんですが、サイズ教えていただいたらそのサイズでご用意いたします！

**Comment by kozaru** [comment]
@asaga 90分になると結構枠が大きくなるので、以下のようにされてはどうでしょうか？
タイムテーブルに掲載する文章は、少し短くしてみましたが、長いままがよいようでしたら、お知らせください！また、ボタンのテキスト：Entryを申込に変更も可能です。文章も含め、文言は統一したほうが良いと思いますので、ご希望を教えて下さい！！！

（少し修正しました！）

## タイムテーブル

### 7/11まで

Scratchって何？ 初めてのCoderDojo! −オトナもコドモもニンジャになろう−
・事前のエントリー（申込）とPCを持参頂く必要があります。
・定員：大人６名、子供６名（大人だけ、子供だけでも参加可能です）
・エントリーは7/11開始予定です。

<img width="434" alt="2016-07-04 7 58 22" src="https://cloud.githubusercontent.com/assets/2457308/16548061/2c78b212-41bd-11e6-81e7-4ff9c413b637.png">

### 7/11より

Scratchって何？ 初めてのCoderDojo! −オトナもコドモもニンジャになろう−
・事前のエントリー（申込）とPCを持参頂く必要があります。
・定員：大人６名、子供６名（大人だけ、子供だけでも参加可能です）

Entry:大人 Entry:子供（→これ分けるんですよね？）

<img width="438" alt="2016-07-04 7 58 37" src="https://cloud.githubusercontent.com/assets/2457308/16548060/2749c2cc-41bd-11e6-84e2-255f759c7827.png">

## ポップアップ

■タイトル
Scratchって何？ 初めてのCoderDojo! −オトナもコドモもニンジャになろう−

■説明文
CoderDojoに参加する子供達のことをNinja（ニンジャ）と呼びます。本来Dojoは小学生〜高校生くらいまでの子供達のための場所ですが、このワークショップでは特別に大人にもニンジャになってもらい、子供達と一緒にDojoを体験していただきます。内容は初めてScratchに触る子供達を対象とした簡単なプログラミング講座です。何が出来るかな？子供は楽しく！大人は忘れた子供心を取り戻そう！

注意事項：
・本ワークショップは事前のエントリー（申込）が必要です。
・大人だけ、子供だけでも参加可能です。
・各回大人６名、子供６名。
・PCを持参頂く必要があります。
・詳細はエントリー（申込）ページをご覧下さい。エントリーは7/11開始予定です。

**Comment by ixkaito** [comment]
@akari-doi 
幅 640px 以上あれば大丈夫です。縦横比は 3:2 の予定。

@kozaru 
タイムテーブルに説明文を掲載するんでしたっけ？
Entry ボタンは一個だと思います。リンク先同じなので。

**Comment by asaga** [comment]
@kozaru そちらの内容でお願いします！

**Comment by kozaru** [comment]
当初はその予定ではなかったのですが、エントリーの条件がいろいろあるので、注意書きは、ボタンの近くにもあったほうが良いと思ったのですが、いかがでしょうか？

**Comment by kozaru** [comment]
あと、余白が大きくなるのも理由の一つです。

**Comment by kozaru** [comment]
@asaga 
ご賛同ありがとうございます。デザイン的な部分も含め、相談して決めますね。
決まったら、改めて連絡します。

@ixkaito 
余白部分に、定員や申込条件等を記載する件、エントリーの条件がいろいろあるので、注意書きは、ボタンの近くにもあったほうがわかりやすい＋余白（特にスマフォの場合）多いのでと思っての提案でした。デザインやその他の意図でやめたほうがよければ、なしでいいです。写真のレイアウトが今回あるので、更新作業も含めておねがいしてもよいでしょうか？

**Comment by akari-doi** [comment]
@kozaru @ixkaito 画像ですが、https://drive.google.com/drive/u/0/folders/0B9m59ut-K_FzSzhuRlpGUnRaZEU
この中に「workshop.jpg」としておいておきました。
3:2にするのに、642×428にしていますー。

**Comment by asaga** [comment]
@kozaru 
この件って今どんな状況でしょうか？

**Comment by kozaru** [comment]
@asaga 
遅くなっていて申し訳ないです。写真のレイアウトが入るので、@ixkaito にお願いしています。
でき次第、ご連絡しますね。
今しばらくお時間くださいませ。

**Comment by kozaru** [comment]
@asaga テキストだけプレビューに流し込んでおきました。
@ixkaito 写真のレイアウトや、タイムテーブルの文章などの修正（入れるかどうかもいれて）と、修正後@asaga にご連絡お願い致します。

**Comment by asaga** [comment]
@kozaru @ixkaito ありがとうございますm(_ _)m
写真のレイアウトに時間かかりそうでしたら、7/11に申し込みボタンを付けるタイミングで写真を載せるのでも良いかなと思っています。

**Comment by kozaru** [comment]
@ixkaito 写真お時間掛かりそうですか？

**Comment by ixkaito** [comment]
@asaga @kozaru @akari-doi 
お待たせしました。プレビューをご確認ください。
http://dojocon-japan.github.io/

**Comment by asaga** [comment]
@ixkaito @kozaru @akari-doi  ありがとうございます。問題ありません！
