### ISSUE TITLE
【セッション概要】寺園さん

### ISSUE THREAD

**Issue by Ippey** [dojocon-japan/dojocon-japan.github.io#182]
セッションタイトルと概要の更新をお願いします。

セッション名：Minecraftによるプログラミング学習の可能性

セッション概要：
発売からもう７年も経つのに世界中で未だにファンが絶えないMinecraftですが、これは日本でも子供たちの間で大人気です。
そんなMinecraftを、ゲームとしてだけでなく、教材としてして使うことができないか、あちらこちらで実験的なイベントやプロジェクトがたちあがっています。それはCoderDojoでも同じで、ときどき僕もMinecraftのModプログラムを作りたいという忍者がいます。
本セッションではModプログラムとはどういうものなのか、またMinecraftを通じてプログラミングを学ぶことが可能なのかどうか、一人の忍者との出会いを通じて気づいた事をお話したいと思います。

**Comment by kozaru** [comment]
@Ippey プレビューにアップしています！ご確認お願いします。

**Comment by Ippey** [comment]
OKです。本番反映お願いします。

**Comment by kozaru** [comment]
@ixkaito https://github.com/dojocon-japan/dojocon-japan.github.io/pull/184
releaseブランチへはマージできたのですが、本番リポジトリに反映されませんでした。
エラーが出ているようです。よくわからないので、ご確認おねがいできないでしょうか？

**Comment by ixkaito** [comment]
@kozaru @Ippey 
問題なく公開されましたので close します。
