### ISSUE TITLE
【スポンサーロゴ掲載の依頼】KDDIコミュニケーションズさん

### ISSUE THREAD

**Issue by okhiroyuki** [dojocon-japan/dojocon-japan.github.io#188]
KDDIコミュニケーションズさん

シルバーの１番目です。

依頼内容の詳細
https://docs.google.com/spreadsheets/d/1EScDR67LrJGzcgGuVBLK7gfhdJzYB5pZeJe9a80vyKY/edit#gid=0

よろしくお願いします。

**Comment by ixkaito** [comment]
@okhiroyuki 
了解です。シルバーって5つで全部ですか？

**Comment by ixkaito** [comment]
@okhiroyuki @michieymt 
あと `alt` タグは「株式会社KDDIウェブコミュニケーションズ」でいいんですかね？
ロゴとリンク先が完全 CPI なので「レンタルサーバー CPI」の方がいいような気がしますが…

**Comment by okhiroyuki** [comment]
@ixkaito そうなんです、今Slackで書こうと思ったんですが、都合により５枠になってしまいました。
申し訳ないです。
もう、５枠から変更はありません。

あと、altタグですが、下記のような連絡しかもらってないです。
一応、「株式会社KDDIウェブコミュニケーションズ」でやって、メールで確認します。
それで、よろしいでしょうか？

> 掲載社名：株式会社KDDIウェブコミュニケーションズ
> リンク先URL：http://www.cpi.ad.jp/

**Comment by ixkaito** [comment]
@okhiroyuki 了解です

**Comment by ixkaito** [comment]
@okhiroyuki ちなみに、ひとつだけ改行になってしまうので、5つを1行に詰めても大丈夫ですかね？ブロンズとの差が少なくなりますが。とりあえずプレビューに上げました。
https://dojocon-japan.github.io/

**Comment by okhiroyuki** [comment]
@ixkaito いや、いいんじゃないですか。
上にあるので、それはもう良しとしましょ！

**Comment by ixkaito** [comment]
@okhiroyuki では公開しちゃって大丈夫ですか？

**Comment by okhiroyuki** [comment]
@ixkaito はい、お願いいたします。
