### ISSUE TITLE
Session ポップアップ：Speakerが複数の場合のパターン

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#19]
39d8685

上記のコミット分です。

チャンピオンパネルディスカッション[15:40-16:20]
をサンプルで入れています。複数人数の場合、Avator間にスペースが欲しいです。

また、名前の区切りは、,（カンマ）でよいでしょうか？

@mayurin マージされて、プレビューURLで見れるようになったら、確認をおねがいしたいです。

**Comment by kozaru** [comment]
@ixkaito このパターン#21 のプルリクには入ってないので、
39d8685
のコミットで確認お願いします。

**Comment by ixkaito** [comment]
@kozaru 
`、` でいいんじゃないかな？
CSS を改善しました。`.speaker-avator` に複数の `img` を入れれるようにしました。
