### ISSUE TITLE
参加受付URL

### ISSUE THREAD

**Issue by kwaka1208** [dojocon-japan/dojocon-japan.github.io#190]
遅くなりましたが、参加受付URLが確定しましたのでお知らせします。

DojoCon Japan 2016
http://eventregist.com/e/DojoConJapan2016

ワークショップ１（10:40-12:10）
http://eventregist.com/e/Scratch1

ワークショップ２（12:30-14:00）
http://eventregist.com/e/Scratch2

ワークショップ３（14:20-15:50）
http://eventregist.com/e/Scratch3

上記のURLはすでにアクセス可能で、申し込みも可能な状態です。
ただし、EventRegistのイベントリストには非表示としていますので、URLを知っている人しかアクセスできません。公式サイトの掲載後、イベントリスト表示有りに変更します。

**Comment by ixkaito** [comment]
プレビューに上げました。問題なければ0時過ぎに公開します。
https://dojocon-japan.github.io/

**Comment by kwaka1208** [comment]
確認しました、リンクはOKです。
タイムテーブルの中の、「エントリーは7/11開始予定です。」はもう不要なので削除していただけますか。

**Comment by ixkaito** [comment]
削除しました
