### ISSUE TITLE
【プロフィール】Rossさんのプロフィール修正

### ISSUE THREAD

**Issue by Ippey** [dojocon-japan/dojocon-japan.github.io#195]
以下の文章を削除してもらえますでしょうか？

”登壇方法は現在調整中
Presentation style is being adjusted”

**Comment by kozaru** [comment]
できたら連絡します。

**Comment by kozaru** [comment]
fix 入れるとクローズされちゃうんでした。

@Ippey 修正しました。プレビューでご確認ください。

**Comment by kozaru** [comment]
@Ippey アップしました！

@ixkaito releaseをmasterにマージしてしまって、revert したので、treeが複雑になってます。ごめんなさい。
