### ISSUE TITLE
Exhibitionへの追加(RALLY)

### ISSUE THREAD

**Issue by asaga** [dojocon-japan/dojocon-japan.github.io#199]
ExhibitionへRALLY企画を追加したいと思います。以下の内容でお願いできますしょうか。

タイトル：会場を回ってスタンプを集めよう！
説明文：スタッフに声をかけて、スタンプを集めよう。全部集めると特典がありますよ！！

画像
https://drive.google.com/file/d/0B0csOe7BSg0pUGFucDhIWGVRNUk/view

**Comment by kozaru** [comment]
@akari-doi リストに画像を追加したので、加工おねがいしたいです！

**Comment by kozaru** [comment]
@asaga タイトルと文章に「RALLY」が入ってないですが、写真で表現ってイメージかなと思っています。入れたほうがよかったら、お知らせくださいね！

**Comment by akari-doi** [comment]
@kozaru 画像入れました！
ほんとだ、RALLYって入ってないですね。写真もけっこうなにかわからない写真なので入れたほうがよさそう。

**Comment by asaga** [comment]
@akari-doi @kozaru 
説明文が短めなので、そこに付け足す感じにしたいと思います。

■変更前
スタッフに声をかけて、スタンプを集めよう。全部集めると特典がありますよ！！

■変更後
モバイルスタンプラリーサービス「RALLY」を使ったスタンプラリーを開催します！
スタッフに声をかけて、スタンプを集めよう。全部集めると特典がありますよ！！

**Comment by kozaru** [comment]
@akari-doi ありがとうございました。
@asaga プレビューにアップしました！

**Comment by asaga** [comment]
@kozaru すいません、一点忘れておりました。末尾に以下を追記頂いて良いでしょうか。

（協力：株式会社フェイスクリエイツ）

**Comment by kozaru** [comment]
@asaga プレビューに追加しました！

**Comment by asaga** [comment]
@kozaru 
ありがとうございます！
来週水曜日の夜に先方とオンラインMTGを実施する事になりまして、そこで最終の確認をしたいので、公開はちょっとお待ち頂いて良いでしょうか。
対応進めて頂いたのにすみません。

**Comment by kozaru** [comment]
@asaga 承知しました！

**Comment by kozaru** [comment]
@asaga 一旦プレビューから削除しました。

**Comment by kozaru** [comment]
@asaga 修正後、RALLYさんに確認が入る場合、プレビューではなく、スクリーンショット（画像）での確認でおねがいしたいので、修正の際、確認が入るようでしたら、お知らせお願い致します！

**Comment by asaga** [comment]
@kozaru 遅くなりましたが、こちらの内容でお願いしますm(_ _)m

あと、一点ご要望を頂いているのですが、（協力：RALLY）のRALLYをリンク（https://rallyapp.jp/）にする事は可能でしょうか？

---

＜モバイルスタンプラリー＞会場に隠れた風魔たちを見つけて、限定ステッカーをゲットしよう！
初開催の DojoCon Japanに風魔たちも参戦！どうやら展示されている作品を盗もうと企んでいるみたい。目撃情報をもとにイベント会場に隠れている風魔たち4人を見つけ出し、悪巧みを阻止しよう！
（協力：RALLY）
![rally](https://cloud.githubusercontent.com/assets/8414384/17806215/2c421d4c-663e-11e6-85ac-35ae25ea51e2.jpg)

**Comment by kozaru** [comment]
@asaga プレビューにアップしました！

**Comment by asaga** [comment]
@kozaru ありがとうございます。問題ないです！

**Comment by kozaru** [comment]
@asaga 公開しました！

**Comment by asaga** [comment]
@kozaru ありがとうございました！
