### ISSUE TITLE
行動規範の追加

### ISSUE THREAD

**Issue by okhiroyuki** [dojocon-japan/dojocon-japan.github.io#2]
# 修正箇所

カテゴリーの追加？
# 修正内容

[こちら](https://docs.google.com/document/d/154wbHL2NXAuObXPEX5PYchHXm23ZVkXKt9FvfPH9PMk/edit)の行動規範を追加ください。

**Comment by ixkaito** [comment]
@akari-doi @mayurin 本件どうしますか？

**Comment by akari-doi** [comment]
@ixkaito すっかり行動規範のことは頭になかったです。すみません…。
@okhiroyuki 今ティザーではどうなってますか？こちら例えばフッターにリンクを配置して、そこからこのドキュメントに飛ばすとかでも問題ないですか？

**Comment by ixkaito** [comment]
@okhiroyuki @akari-doi 
ちなみに行動規範だけのページは用意できます。

**Comment by akari-doi** [comment]
@ixkaito @okhiroyuki カイトさん！ありがとうございます！
細谷さんが行動規範のページ用意できるならそうしてもらってとのことなので、お願いできますでしょうか。
よろしくお願いいたします。
リンク元はフッターあたりに配置とかできそうでしょうか。
フッター以外にこちらに配置したほうがいいのではというところがあればカイトさんにお任せしたいと思います。
