### ISSUE TITLE
スピーカーのmoreをクリックした後の挙動

### ISSUE THREAD

**Issue by akari-doi** [dojocon-japan/dojocon-japan.github.io#20]
スピーカーのmoreボタンをクリックした後、ポップアップされますが、2行目（4人目）まで矢印で送るとポップアップ画面が矢印と×だけになります。
で、その画面を閉じたらmoreボタンがなくなります。
これ画像添付できるんですかね、すみません言葉じゃわかりづらいですが。

Mac、Chrome最新版で見てます。iPhoneで見てもなりました。

**Comment by kozaru** [comment]
@akari-doi サンプルでは3人分しかポップアップが用意されていないためではと思います。

@ixkaito 上記のお返事でよければ、確認後closeおねがいしたいです。

**Comment by akari-doi** [comment]
@kozaru そうなんですね、大変失礼しました！

**Comment by ixkaito** [comment]
@akari-doi さんへ
@kozaru さんのいうとおりです。Close します。
