### ISSUE TITLE
【セッション】スピーカープロフィール、セッション概要更新

### ISSUE THREAD

**Issue by Ippey** [dojocon-japan/dojocon-japan.github.io#205]
パネルディスカッション登壇者のプロフィール情報を入手しましたので
更新お願いします。

なお、山田さんはプロフィール写真なしとなりましたので、お手数ですが
代わりの画像（スタッフと同じような感じ）でご対応お願いします。

パネルディスカッション追加メンバーは
・田重田さん
・牧さん
・山田さん
・角田
です。

**Comment by kozaru** [comment]
@akari-doi 田重田さん、牧さんの画像の加工お願いします。シートに追加済みです。

**Comment by kozaru** [comment]
@mayurin @akari-doi 
山田さんはプロフィール画像なしのため、代わりの画像をおねがいしたいです。
どちらにお願いするのがよいかわからなかったので、お二人にメンションしました。

**Comment by kozaru** [comment]
@Ippey 
セッション概要、スプレッドシートで更新されていなかったのですが、今回のIssueでは公開せず、プロフィールの公開のみでよいでしょうか？
タイムテーブル内のスピーカー名は変更予定です。

**Comment by akari-doi** [comment]
@Ippey スタッフのプロフィールなし画像は陰陽マークに「STAFF」としてありますが、SPEAKERとかにしときます？
というか、なんでもいいのでご用意いただくほうがいいと思うんですけどね…(･Θ･;)
スピーカーの大きい画像がこれって微妙だなぁと…。
上記で大丈夫なら特に手間は発生しませんしすぐ作らせていただきますが。準備に時間がかかりそうとかならこれでしちゃいますけど、一応、どうかなって。

**Comment by Ippey** [comment]
@akari-doi 用意してもらったんですけど、かなり小さくてあまり使えそうな感じじゃなかったんです…
一応ご用意しました。

https://drive.google.com/open?id=0B6jewzM1ftDiekJYNmcyem5GLUE

**Comment by mayurin** [comment]
@akari-doi @Ippey ちょっと私の方で一回預かってもいいですか？

**Comment by kozaru** [comment]
@mayurin @akari-doi @Ippey 画像の件、決まったら、メンション入れてください。よろしくお願いいたしいます。

**Comment by Ippey** [comment]
@kozaru セッションの概要を変更しましたので、ご確認お願いします。

**Comment by akari-doi** [comment]
@mayurin はい、私は大丈夫ですが、なんか新たに作られる感じですかね。

**Comment by mayurin** [comment]
@akari-doi 今ちょっとアイコン作ってみてます。

**Comment by kozaru** [comment]
@Ippey 確認しました！
写真決まったら、セッションと合わせて更新後、お知らせします。
スケジュールなんですが、今プレビューで承認待ちデータがあり、その確認が水曜日の夜になる予定です。なので、アップが木曜日以降になりそうなのですが、もしお急ぎでしたら、調整しますので、お知らせください！

**Comment by mayurin** [comment]
![speaker_f](https://cloud.githubusercontent.com/assets/3609039/16940509/69e00100-4dc5-11e6-902d-d0a524abb146.jpg)
![speaker](https://cloud.githubusercontent.com/assets/3609039/16940510/6a08bdc0-4dc5-11e6-8b56-6d72e585f3f8.jpg)
@Ippey @akari-doi 作ってみました。どでしょう。

**Comment by akari-doi** [comment]
@mayurin @Ippey 山田さんが、いただいた写真が小さい点を指摘しても画像を出せない（写真がないので適当に掲載してください）という感じなのであれば、まゆりんが作ってくださった画像を使っていただいたらいいかなと思います。

**Comment by akari-doi** [comment]
今の状況がどちらなのか（小さいってすでに指摘済みなのかそうでないのか）がわからなかったので…！

**Comment by mayurin** [comment]
あ、そっか。それを先聞いたらよかったね。

**Comment by kozaru** [comment]
@mayurin かわいい！ありがとうございます！

@Ippey 写真使用にあたって、ダミーを使うか、いただいた写真を使うかのご判断よろしくお願いいたします！

**Comment by akari-doi** [comment]
@mayurin ごめんなさいよく考えたらそうだなと思って＞＜

**Comment by mayurin** [comment]
状況によって、写真使えないとかだったら使ってやってください。

**Comment by Ippey** [comment]
@mayurin @akari-doi 写真は小さいので大きいの下さいと連絡したのですが、結果ちょうど良いのがないので、画像なしにしてもらえないかと相談されていました。
なので、作っていただいた画像で問題ないです。

**Comment by kozaru** [comment]
@Ippey 山田さんをまゆりんに作ってもらった画像で、その他はいただいた写真とテキストで更新で良いでしょうか？お返事いただいたら、作業する予定です。

また、今日は作業できるかどうかわからないです。できたら連絡します。

**Comment by Ippey** [comment]
@kozaru OKです。よろしくお願いします。
今日中でなくても大丈夫です。

**Comment by akari-doi** [comment]
@kozaru まきさん、たじゅうたさん作成しました。
ただ、まきさんの写真はお子さんと写っており、どうしてもお子さんをいれないようにしようと思うとかなりイケてない画像になっています…。
@Ippey まきさん、一応作成しましたがお子さん入れないほうがいいですよね…。とりあえずこれで公開していただいて、確認して嫌なら他の写真をご用意いただく感じでいいですかね。
毎回写真問題が多すぎるw

**Comment by kozaru** [comment]
@akari-doi ありがとー！
@Ippey 指示がなければ、一旦いただいた写真で作成しますね。

**Comment by kozaru** [comment]
@Ippey プレビューにアップしているのでご確認お願いします。

**Comment by Ippey** [comment]
@kozaru OKなのでタイミングいい時にアップおねがいします。

**Comment by kozaru** [comment]
@Ippey ご確認ありがとうございました。
