### ISSUE TITLE
【In-Kind Sponsorのロゴ掲載】翔泳社さん

### ISSUE THREAD

**Issue by okhiroyuki** [dojocon-japan/dojocon-japan.github.io#206]
翔泳社さん

In-Kind Sponsorの１番目です。

依頼内容の詳細
https://docs.google.com/spreadsheets/d/1EScDR67LrJGzcgGuVBLK7gfhdJzYB5pZeJe9a80vyKY/edit#gid=0

よろしくお願いします。

**Comment by kozaru** [comment]
@ixkaito 以下現在進行中の更新内容の連絡です。
#199 がプレビュー状態で、7/20夜のオンラインミーティングで確認後、リリース予定です。
#205 はどの画像を使うか確認後、プレビュー掲載の作業予定です。

**Comment by ixkaito** [comment]
@okhiroyuki プレビューに上げました。
https://dojocon-japan.github.io/

**Comment by okhiroyuki** [comment]
@ixkaito
ありがとうございます。
いいと思います！
これ、他の人にも確認してもらいますね。

@asaga @tkc49 問題ないか、確認ください！

**Comment by kozaru** [comment]
@ixkaito #199に修正が入り、まだ公開できない状態なので、一旦masterから、revertしました。
In-kind公開されるようでしたら、よろしくお願い致します。

**Comment by okhiroyuki** [comment]
@ixkaito 確認とれましたので、公開お願いいたします！

**Comment by ixkaito** [comment]
@kozaru そちらの issue がすべて公開できるようになったら一緒に公開してもらって大丈夫ですよ。

**Comment by kozaru** [comment]
@ixkaito その他のIssueは公開できるようになるのが、先になりそうです。
今はIn kindのみプレビューにある状態なので、公開しておきますね。

**Comment by kozaru** [comment]
@okhiroyuki 公開しましたー！
