### ISSUE TITLE
【In-Kind Sponsorのロゴ掲載】XOOMSさん

### ISSUE THREAD

**Issue by okhiroyuki** [dojocon-japan/dojocon-japan.github.io#208]
XOOMSさん

In-Kind Sponsorの3番目です。

依頼内容の詳細
https://docs.google.com/spreadsheets/d/1EScDR67LrJGzcgGuVBLK7gfhdJzYB5pZeJe9a80vyKY/edit#gid=0

よろしくお願いします。

**Comment by ixkaito** [comment]
@okhiroyuki プレビューに上げました。
https://dojocon-japan.github.io/
