### ISSUE TITLE
In-kindスポンサー掲載（Mabee）

### ISSUE THREAD

**Issue by asaga** [dojocon-japan/dojocon-japan.github.io#213]
https://docs.google.com/spreadsheets/d/1EScDR67LrJGzcgGuVBLK7gfhdJzYB5pZeJe9a80vyKY/edit#gid=0

こちらの24行目のノバルス株式会社さんお願いします。
ロゴ画像はGoogle Driveの方はいろいろ圧縮されてる常態なので、Backlogに添付のファイルをお使い頂ければと思います。
 logo_novars.jpgか logo_novars_High.jpgです。（両方同じ画像っぽいですが・・・）

**Comment by asaga** [comment]
Backlogはこちら。
https://megumilog.backlog.jp/view/DOJOCON-507

**Comment by ixkaito** [comment]
@asaga プレビューに上げました
https://dojocon-japan.github.io/#sponsors

**Comment by asaga** [comment]
@ixkaito ありがとうございます。OKです。

**Comment by ixkaito** [comment]
@asaga 公開しました

**Comment by asaga** [comment]
@ixkaito ありがとうございました！
