### ISSUE TITLE
Exhibitionへの追加(Mabee)

### ISSUE THREAD

**Issue by asaga** [dojocon-japan/dojocon-japan.github.io#214]
タイトル：
シャカシャカ振ってビュンビュン飛ばせ！カーレースでライバルに打ち勝て！

掲載文言：
MaBeeeとスマホを連動させて、ミニ四駆をコントロールしよう！
シャカシャカとスマホを振ってスピードをコントロールし、コースアウトせずにライバルに打ち勝とう！（協力：ノバルス株式会社）

画像
https://megumilog.backlog.jp/view/DOJOCON-507
Mabeeのロゴ（mabeeelogo_High.ai）でお願いします。

**Comment by kozaru** [comment]
@asaga 
このプレビューもMabeeさんに確認されますか？
その場合は、その他の更新と重なる可能性があるので、プレビューではなく、画像で確認いただきたいです。

**Comment by kozaru** [comment]
@asaga このプレビューもMabeeさんに確認されますか？
その場合、その他の更新が重なる可能性があるので、その部分のキャプチャを送って確認してもらってから、プレビューにマージしてもいいですか？

**Comment by kozaru** [comment]
@akari-doi 画像の加工お願い致します。

**Comment by asaga** [comment]
@kozaru 確認無しでOKです

**Comment by akari-doi** [comment]
@kozaru 完了しました！

**Comment by akari-doi** [comment]
あ、ごめんなさい、ロゴがよかったんですね、見てませんでした！やりなおします！

**Comment by akari-doi** [comment]
@kozaru 今度こそ完了しました！

**Comment by kozaru** [comment]
@akari-doi ありがとー！

**Comment by kozaru** [comment]
@asaga プレビューにアップしているのでご確認お願いします。
画像...背景がないのですが、よいでしょうか？

**Comment by asaga** [comment]
@kozaru 背景については念のため確認中です

**Comment by kozaru** [comment]
@asaga OKでたら、その他も含めて、公開予定なので、お時間かかりそうなら、教えてくださーい！

**Comment by asaga** [comment]
@kozaru OKでましたので、公開お願いします！

**Comment by kozaru** [comment]
@asaga ありがとうございます！
