### ISSUE TITLE
Exhibitionへの追加(コモジラ)

### ISSUE THREAD

**Issue by asaga** [dojocon-japan/dojocon-japan.github.io#215]
タイトル：
パラパラアニメーションで世界に一つだけの海を作ろう！

掲載文言：
パラパラマンガをつくるような感覚で自分の好きなアニメーションを描き、みんなで一つの大きな映像作品を作ります。
世界に一つだけの海を、みんなで作りあげてみませんか？（協力：コモジラ研究所）

画像
https://megumilog.backlog.jp/view/DOJOCON-439
こちらの本文に添付の画像（mozilla_photo.jpg）でお願いします。

**Comment by kozaru** [comment]
@akari-doi 画像加工おねがいしたいです！スプレッドシート追加しました！

**Comment by akari-doi** [comment]
@kozaru 完了しました！

**Comment by kozaru** [comment]
@akari-doi いっぱい、ありがとうございました！

**Comment by kozaru** [comment]
@asaga プレビューにアップしているのでご確認お願いします。

**Comment by asaga** [comment]
@kozaru こちらOKです
