### ISSUE TITLE
【スポンサーロゴ掲載の依頼】ネクストジェネレーション株式会社

### ISSUE THREAD

**Issue by michieymt** [dojocon-japan/dojocon-japan.github.io#217]
ネクストジェネレーション株式会社
ブロンズの7番目、一番最後です。

依頼内容の詳細
https://docs.google.com/spreadsheets/d/1EScDR67LrJGzcgGuVBLK7gfhdJzYB5pZeJe9a80vyKY/edit#gid=0

next_G_banner_2.jpg
という方です。

よろしくお願いします。

**Comment by ixkaito** [comment]
@michieymt プレビューに上げました
https://dojocon-japan.github.io/#sponsors

**Comment by michieymt** [comment]
@ixkaito 
ありがとうございます。
確認しました。
公開おねがいします。

**Comment by ixkaito** [comment]
公開しました

**Comment by michieymt** [comment]
ありがとうございます。
@ixkaito
