### ISSUE TITLE
【セッション】スピーカープロフィール、タイムテーブル変更

### ISSUE THREAD

**Issue by Ippey** [dojocon-japan/dojocon-japan.github.io#221]
倉本さんが追加になりましたので、
倉本さんのプロフィール追加、『有償・無償〜』の概要変更をお願いします。
タイミングはいつでも構いません。

**Comment by kozaru** [comment]
承知しました。
先にカイトさんに Sponsor周りの更新をお願いしようと思うので、そのあとで、修正しますね。

**Comment by kozaru** [comment]
@akari-doi 写真の加工よろしくお願いします。スプレッドシートに追加しました！

**Comment by kozaru** [comment]
すみません。ボタン押し違えた。。。

**Comment by kozaru** [comment]
@Ippey 
プレビューに追加しました。掲載順ご確認お願いします。

@akari-doi 
写真が真四角だったのでリサイズしていれました。補正や調整があれば、連絡ください。

**Comment by Ippey** [comment]
@kozaru コンテンツ的には問題ないですが、表示場所変えるかもしれないです。

@tkc49 谷岡さんの左にしますか？

**Comment by kozaru** [comment]
@Ippey #243にも書きましたが、こちらに修正が入るようなら、修正後、まとめてreleaseへマージしようと思っていますが、それでよいでしょうか？

**Comment by tkc49** [comment]
@kozaru @Ippey 
はい、谷岡さんの左でOKです

**Comment by kozaru** [comment]
@tkc49 了解です！
@Ippey 修正しました。

**Comment by kozaru** [comment]
@Ippey 公開しますね。

**Comment by kozaru** [comment]
@Ippey @tkc49 公開しました。
