### ISSUE TITLE
Individual Supportersの掲載

### ISSUE THREAD

**Issue by okhiroyuki** [dojocon-japan/dojocon-japan.github.io#224]
以前、ご相談していたクラウドファンディングの御礼の一つとして、Webへのお名前掲載をそろそろ行っていきたいと思います。
もう、ある程度落ち着いてきたいと思いますので、下記wikiにありますリストをもとに作成いただければと思っております。
https://megumilog.backlog.jp/wiki/DOJOCON/20_%E3%82%B9%E3%83%9D%E3%83%B3%E3%82%B5%E3%83%BC

なお、掲載順はランクなど関係なく、ご支援順でお願い致します。

**Comment by kozaru** [comment]
@ixkaito 今日は作業できないので、今日作業されるようなら、お先にどうぞ！作業が先になるようでしたら、教えてくださーい。

**Comment by ixkaito** [comment]
@okhiroyuki プレビューに上げました。Takashi Hosoya が二人いたのであとのほうを消しました。
https://dojocon-japan.github.io/#sponsors

**Comment by okhiroyuki** [comment]
@ixkaito 細谷さん表記が2つ混ざっていたのですが、tanaka0726さんと、園田 浩一に挟まれているほうは、**クリエーションオフィス春夏秋冬** でお願いいたします。

細谷さんが、代役として寄付されておられました。
お手数おかけしますが、よろしくお願いいたします。

**Comment by okhiroyuki** [comment]
@tkc49 上記の対応で問題ないですよね？
あと、プレビュー確認ください！

**Comment by tkc49** [comment]
@okhiroyuki 確認しました！
｢クリエーションオフィス春夏秋冬｣さんだけ追記してくれたらOKです！

**Comment by ixkaito** [comment]
@okhiroyuki @tkc49 公開しました
