### ISSUE TITLE
【セッション】セッション概要追加：ニンジャ作品発表

### ISSUE THREAD

**Issue by Ippey** [dojocon-japan/dojocon-japan.github.io#225]
ニンジャ作品発表について、概要ができましたので
タイムテーブルへ追加お願いします。

https://docs.google.com/spreadsheets/d/1H5AWrFv6R8_zse2z2EWQcGUNzlhlr-L7x8FAQdbo0pw/edit#gid=1910163359

14:35〜14:55　ニンジャ作品発表

アップのタイミングは、いつでも結構です。

**Comment by kozaru** [comment]
@Ippey 承知しましたー。その他の依頼もあるようなので、しばしお待ち下さい。プレビューになったら、こちらとSlackでお知らせします。

**Comment by kozaru** [comment]
＠Ippey 
プレビューに追加しました。ご確認お願い致します。

**Comment by Ippey** [comment]
@kozaru OKです！

**Comment by kozaru** [comment]
@Ippey 公開しました。
