### ISSUE TITLE
タイムテーブルの追記

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#23]
公開時、タイムテーブルは未完成の状態になりますので、その旨を記載する必要があるかと思います。

backlogのチケット：DOJOCON-215 で、タイムテーブルの横のテキストとして記載予定でしたが、消えていました（汗）

デザインが途中で変わったのかなぁと思っていますが、注記は必要だと思っています。

**Comment by ixkaito** [comment]
@kozaru

テキストが消えているのはあるかどうかまだわかってなかったので入れてないだけです。必要であればすぐ入れれます。

テキストをこの issue に載せるか、リンクしてもらえれば大丈夫です。

**Comment by ixkaito** [comment]
@pictron さんより from #24 

> 企画マターなんですが、ちょっとこのチケットの答えが固まらないので
> https://megumilog.backlog.jp/view/DOJOCON-215
> 仮に当たり障りのないものを考えたので、これでいきましょう。後で企画から変更などあれば言ってもらいましょう。
> 
> ```
> 記載の内容を当日やむを得ず変更する場合があります。
> 体験型のエキシビジョンで人数を制限する場合があります。
> 事前申込が必要なプログラムがございます。
> 詳細をお知りになりたい場合はお問い合わせください。
> ```
> 
> 改行なしでもリスト形式でもどちらでも大丈夫です。
