### ISSUE TITLE
10時開場？

### ISSUE THREAD

**Issue by ixkaito** [dojocon-japan/dojocon-japan.github.io#24]
@tkc49 @Ippey @kwaka1208 @kozaru 
10時開場なら、タイムテーブルの上空いてますので入れますか？

**Comment by pictron** [comment]
企画マターなんですが、ちょっとこのチケットの答えが固まらないので
https://megumilog.backlog.jp/view/DOJOCON-215
仮に当たり障りのないものを考えたので、これでいきましょう。後で企画から変更などあれば言ってもらいましょう。

```
記載の内容を当日やむを得ず変更する場合があります。
体験型のエキシビジョンで人数を制限する場合があります。
事前申込が必要なプログラムがございます。
詳細をお知りになりたい場合はお問い合わせください。

```

改行なしでもリスト形式でもどちらでも大丈夫です。

**Comment by ixkaito** [comment]
@pictron 
ありがとうございます！でもこれたぶん #23 の内容だと思いますので、そちらに追記します。

**Comment by pictron** [comment]
あれ、失礼しました。

**Comment by tkc49** [comment]
@ixkaito レスが遅くてすいません。
今確認できました！
せっかく空いてるので、「開場」と入れて頂ければと思います！
宜しくお願いします！

@kwaka1208 10時開場で良かったですよね？
9時〜10時の1時間でもろもろ準備ということでOKでしたよね?

**Comment by kwaka1208** [comment]
@tkc49 はい、大まかな進行は以下の通りです。
- 9:00〜10:00 準備
- 10:00〜10:30 開場・受付
- 10:30〜16:30 イベント本編
- 16:30〜　撤収

**Comment by tkc49** [comment]
@kwaka1208 ありがとうございます！
