### ISSUE TITLE
NEWSのアイキャッチ画像差し替えお願いします

### ISSUE THREAD

**Issue by mayurin** [dojocon-japan/dojocon-japan.github.io#243]
https://drive.google.com/folderview?id=0B-O-Ui4qJxjLLWs0eC1qOGxKeU0&usp=sharing
サイズをW600px→W940pxにしました。
ファイル名は現在アップされているものを使っているので、差し替えてもらえればいいかなーと思います。

**Comment by kozaru** [comment]
@mayurin 画像ありがとうございます。
@Ippey どうしましょう？どちらでやりましょうか？
今プレビューに上がっている分があるので、それの確認が終わって作業しようかなと思っています。

**Comment by kozaru** [comment]
@mayurin Newsの更新は、広報の@Ippey にお願いしているのです。css調整とかあったときは、そこでバトンタッチする感じで。（念のため補足）

**Comment by Ippey** [comment]
こちらで差し替えます。

**Comment by Ippey** [comment]
@mayurin @kozaru 
差し替えました。プレビューご確認お願いします。
問題なければリリースにマージします。

**Comment by kozaru** [comment]
@Ippey 問題ないと思います。
OKでしたら、#221 #225 が一緒にmasterにいるので、下記が決定後、releaseにマージ予定です。
https://github.com/dojocon-japan/dojocon-japan.github.io/issues/221#issuecomment-236439527

**Comment by mayurin** [comment]
@kozaru 

> Newsの更新は、広報の@Ippey にお願いしているのです。css調整とかあったときは、そこでバトンタッチする感じで。（念のため補足）

了解です。確認不足ですみません。

**Comment by Ippey** [comment]
@kozaru
OKです。よろしくお願いいたしますー

**Comment by kozaru** [comment]
@Ippey @mayurin 公開しました。
