### ISSUE TITLE
Newsページヘのスポンサーロゴ掲載用css調整

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#245]
7/31のMTGで決まったスポンサーNewsページ作成にあたっての依頼です。
Newsページにlogoを載せるためにcssの調整をおねがいしたいです。

news-logo-check ブランチにNewsのテストページ `2016-08-01-test.md` 内に試してみたコードを入れています。

コミットNo 9f18381 です。

**Comment by kozaru** [comment]
@ixkaito よろしくお願いします。
@okhiroyuki こちらで確認をお願いします。
@Ippey Newsの原稿が届きましたら、こちらの結果を参考に更新していただければと思います。

**Comment by ixkaito** [comment]
@kozaru news-logo-check ブランチに push しました。

**Comment by Ippey** [comment]
@kozaru 
すいません。ちょっと把握できていないんですが、
これって既存の各ニュースにスポンサーのロゴを追加するって話ですか？

**Comment by okhiroyuki** [comment]
@Ippey いや、これってスポンサーに関するブログの掲載ができてなかったので、このあたりでNewsに掲載しようという内容だと理解してます。
違いました？

**Comment by kozaru** [comment]
@Ippey 
先日のMTGで
「スポンサーに関するNews掲載時に、ページ内にスポンサーロゴを掲載したい」
という依頼があり、トップページにあるロゴのHTMLをそのまま使えるか確認しました。
少しcssに調整が必要でしたので @ixkaito におねがいして、調整は完了しました。
そのコードが`news-logo-check`ブランチにあります。

---

@okhiroyuki 原稿作成後、ページ制作依頼は、いつごろになりそうでしょうか？
@Ippey Newsのロゴの掲載方法、どのように連絡するのがよいですか？あるいはNewsページのここに入れて！！！と連絡いただければ、作業します！

**Comment by okhiroyuki** [comment]
@Ippey 原稿のたたきは、下記にあげております。
確認ください。
https://megumilog.backlog.jp/view/DOJOCON-650

@kozaru ページ作成依頼は、原稿が固まったらッて感じでしか考えてません。

**Comment by kozaru** [comment]
@okhiroyuki
了解ですー！

**Comment by Ippey** [comment]
@kozaru @okhiroyuki プレビューにマージしましたのでご確認お願いします。

**Comment by okhiroyuki** [comment]
@Ippey ありがとうございます！ よいと思います！

**Comment by ixkaito** [comment]
@Ippey @kozaru @okhiroyuki シルバースポンサーの見た目がゴールドになってますので直します。

**Comment by kozaru** [comment]
@ixkaito すみません、コピペミスです。ありがとうございました。
