### ISSUE TITLE
【In-Kind Sponsorのロゴ掲載】アシアル株式会社さん

### ISSUE THREAD

**Issue by okhiroyuki** [dojocon-japan/dojocon-japan.github.io#248]
アシアル株式会社さん、献本いただくことになりました。

In-Kind Sponsorの7番目です。

依頼内容の詳細
https://docs.google.com/spreadsheets/d/1EScDR67LrJGzcgGuVBLK7gfhdJzYB5pZeJe9a80vyKY/edit#gid=0

よろしくお願いします。

**Comment by ixkaito** [comment]
@okhiroyuki プレビューに上げました！
https://dojocon-japan.github.io/

**Comment by okhiroyuki** [comment]
@ixkaito ありがとうございます！
問題ありません。

**Comment by okhiroyuki** [comment]
@ixkaito 
すみません、ロゴを「Monaca」のほう（正方形）に修正してください。
https://ja.monaca.io/logos.html

完全に私のミスでロゴデータの指示を間違っておりました。
申し訳ありませんm(__)m

**Comment by ixkaito** [comment]
@okhiroyuki 変更しました。10分後ぐらいに公開されます。
