### ISSUE TITLE
スタッフ画像追加

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#252]

**Comment by kozaru** [comment]
@akari-doi 画像作成依頼をスプレッドシートに記載したのでお時間あるときにお願い致します。

**Comment by akari-doi** [comment]
@kozaru staffフォルダへ作成していれました！よろしくお願いいたします！

**Comment by kozaru** [comment]
@akari-doi ありがとーございました！
