### ISSUE TITLE
【タイムテーブル】セッション追加＆調整

### ISSUE THREAD

**Issue by Ippey** [dojocon-japan/dojocon-japan.github.io#253]
以下の通り、セッションの追加・調整をお願いします。

12:05〜12:15　休憩
12:15〜12:25　内田洋行株式会社様　ご登壇予定

12:45〜12:50　休憩
12:50〜13:05　ルネサスエレクトロニクス株式会社様　ご登壇予定

13:25〜13:30　休憩
13:30〜13:45　DigitalCube 様　ご登壇予定

14:05〜14:10　休憩

16:20〜16:30　表彰式/閉会のことば

休憩部分はテキスト記載なしでよいです。

**Comment by tkc49** [comment]
じゃんけん大会って特に書かなくても良いかな。
※ 他のイベントでもそういうのは見たことないので(^^;)

**Comment by kozaru** [comment]
@Ippey プレビューにアップしていますので、ご確認お願い致します。

**Comment by Ippey** [comment]
@kozaru OKです！リリースにマージお願いします。
