### ISSUE TITLE
【タイムテーブル】登壇者追加

### ISSUE THREAD

**Issue by Ippey** [dojocon-japan/dojocon-japan.github.io#255]
以下のセッションに登壇者の追加をお願いします。

・学生Dojo運営者に聞く!
・有償/無償で何が違う?
安川さん

・チャンピオンパネルディスカッション：
細谷さん、安川さん

それぞれ、安川さんはモデレーターとして参加になります。

**Comment by kozaru** [comment]
@Ippey 

### 安川さんのプロフィール

安川さんは、写真やプロフィールはモデレーターさんなのでなしでよいですか？
安川さんのプロフィールをSpeakersに追加される場合は、原稿をお願いします。

### モデレーター表記

モデレーターとして表記（プロフィールを掲載しない場合）のイメージは下記でよいですか？
プロフィールを掲載する場合は、スピーカー同様写真を入れて、テキストからもリンクを貼る予定です。

・有償/無償で何が違う?
https://drive.google.com/file/d/0B9m59ut-K_FzSzZJRFBoQTZEeDA/view

・チャンピオンパネルディスカッション：
https://drive.google.com/file/d/0B9m59ut-K_FzeHo2M1dEUW9UTTg/view

### その他

#253、プレビューに上がっていて、確認待ちです。
こちらを先にアップした方がよければ、連絡ください。
連絡がなければ、こちらを追加でプレビューに上げます。その場合、どちらもOKになってからの公開になる予定です。

**Comment by Ippey** [comment]
@kozaru 
モデレーター表記は問題ありません。
可能であれば、写真を安川さんのスタッフ画像で入れてもらえればと思います。

#253 は同じタイミングにリリースで問題ありません。

**Comment by kozaru** [comment]
@Ippey プレビューに反映しました。
ご確認よろしくお願いいたします。

**Comment by Ippey** [comment]
@kozaru ありがとうございます。リリースにマージお願いします。
