### ISSUE TITLE
「DojoCon とは？」のテキストとレイアウトの改善

### ISSUE THREAD

**Issue by ixkaito** [dojocon-japan/dojocon-japan.github.io#26]
@pictron 
「DojoCon とは？」のテキストは現在のプレビューの内容で確定でしょうか？もし確定であれば、カンプのときより分量がかなり減りましたので、少しレイアウトの調整が必要かもしれません。

**Comment by pictron** [comment]
今の文字でもオーケーですが、元の文章はもう少しあるので、あと何文字くらいと言ってもらえれば適当に文章追加もできますよ。

**Comment by ixkaito** [comment]
@pictron 
横の写真とテキストが同じぐらいの高さになれば一番キレイに見えると思います。大体250〜300字ぐらいかと思います。

**Comment by pictron** [comment]
これで298文字です。↓
CoderDojoの主催者やメンター、プログラムを学ぶ子供たち、また活動に賛同・協賛する人が数百人集う大きなイベントです。ヨーロッパでは毎年のように開催され、今年もアイルランドのダブリンで3日間開催されます。DojoConでは、アイデアを共有したり、インスピレーションを得たり、コードでしか知らなかった人に会ったり、価値観が共有できる新しい友人に出会えたり、実践的なスキルについて話合ったりすることができます。
CoderDojoをはじめたい人やプログラム教育に興味のある人にとって、コミュニケーションの幅や知識の深さや新たな知見を、また参加したこども達には記憶に残る体験を提供するイベントです。

多い場合は最後の2行はあってもなくてもいいので、それを取ると205文字です。

**Comment by ixkaito** [comment]
@pictron 
ありがとうございます！いい感じに入りました。

**Comment by ixkaito** [comment]
@pictron 
ありがとうございます！いい感じに入りました。
