### ISSUE TITLE
公開時点でのEntryの取り扱い

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#27]
https://megumilog.backlog.jp/view/DOJOCON-402#comment-1142485519

チケットのコメント（上記の前後）で話し合ってます。
@kwaka1208 、公開時点にどういうふうに掲載するか決まったら、ご連絡をお願いします。
表示も含め、要相談でしたら、@ixkaito やデザインチームで相談おねがいしたいです。

**Comment by kwaka1208** [comment]
参加受付は、7月11日で決定です。サイト公開時のデザインについては別途相談しますので、お待ちください。取り急ぎ。

**Comment by kozaru** [comment]
案ですが

Entryボタンを非表示にして、
Newsでその旨を書かれてはどうでしょうか？

**Comment by kozaru** [comment]
プラスヘッダーには、7/11エントリー開始とテキストおいたらどうでしょう？

その場合、デザインも必要かもですが、カイトさんもデザイナーさんなのと時間リソースをかけすぎないために、テキスト表示はカイトさんにお任せしてはどうですか？

**Comment by kwaka1208** [comment]
そういう形でいいと思います、そこに時間をかけるつもりはありません。
デザイン的な面について、どうすればいいのかわからないので、僕が勝手なことを言うわけにはいかないのかなと思っています。

**Comment by kwaka1208** [comment]
はい、それでいいと思います。僕もそこに時間をかけたいわけではないです。
デザイン的な部分は僕がどうこういうわけにもいかない、ということでデザインでお願いしたいということです。

**Comment by kozaru** [comment]
@ixkaito 上記対応お願いできますか？

公開時
- Entryボタン非表示
- ヘッダーのEntryボタン位置に「7/11エントリー開始」とテキストを置く
  （表示方法等はカイトさんにお任せ）

7/11
- Entryボタンの表示
  （上記以外も必要になるかもですが、現時点では詰めていません）
