### ISSUE TITLE
【タイムテーブル】ニンジャ作品発表

### ISSUE THREAD

**Issue by Ippey** [dojocon-japan/dojocon-japan.github.io#277]
スピーカー（ニンジャ）の追加をお願いします。
いずれもスピーカープロフィール、写真なしなのでテキストのみで大丈夫です。

城野 夏妃
田中 たいり
野村 風太 
長谷川 塁音

**Comment by tkc49** [comment]
一応、訂正のログいれておきます。誰かが書き直すとまずいので。
長谷川 塁音 → 長谷川 塁
