### ISSUE TITLE
公開時点でのSession情報・追加/修正

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#28]
@Ippey 公開可能なSessionが公開までにでてきましたら、このIssueでお知らせください！

https://megumilog.backlog.jp/view/DOJOCON-286#comment-1142485930

**Comment by Ippey** [comment]
https://megumilog.backlog.jp/view/DOJOCON-286#comment-1142455086

これのことですよね？

**Comment by kozaru** [comment]
@Ippey そうです！この件、ちょっと早めに相談したいのでSlackにメッセージ入れておきます。

**Comment by kozaru** [comment]
@Ippey 
とがぞのさんのように、個別にIssueを立てられるようなので、このIssueクローズしますね。
その他の件も上記と同様にお願いします。
公開が近づいてきていますので、公開に必須ではない情報の場合、その旨ご記入おねがいしたいです。
