### ISSUE TITLE
【セッション】ロスの分

### ISSUE THREAD

**Issue by Ippey** [dojocon-japan/dojocon-japan.github.io#289]
ぼくのほうでやります。

**Comment by kozaru** [comment]
@Ippey ありがとうございます。
事前にコメントアウトしている部分があるので、よかったら使ってください。
よろしくお願いいたします。

TimeTable
https://github.com/dojocon-japan/dojocon-japan.github.io/blob/release/index.html#L331

Sessionポップアップ
https://github.com/dojocon-japan/dojocon-japan.github.io/blob/release/_includes/sessions.html#L146

Speakerポップアップからのリンク
https://github.com/dojocon-japan/dojocon-japan.github.io/blob/release/_includes/speakers.html#L163

**Comment by kozaru** [comment]
また、更新する際に気をつけていただきたいことを、コメントで入れています。
よろしくお願いいたします。

https://github.com/dojocon-japan/dojocon-japan.github.io/blob/release/_includes/sessions.html#L1

**Comment by Ippey** [comment]
@kozaru 
コメント部分を利用しました。ありがとうございます。
一応ご確認お願いします。

https://dojocon-japan.github.io

**Comment by kozaru** [comment]
@Ippey いくつか直したい所あるのですが、プルリク送っていいですか？
今直してはりますか？

**Comment by kozaru** [comment]
@Ippey pullして、add-session-detail-about-rossブランチ、d11961bをローカルで確認しました。リンクや表示等は問題ないです。ありがとうございました。

**Comment by Ippey** [comment]
@kozaru あ、なんか間違ってました。今は触ってないのですいませんがプルリクお願いします。

**Comment by kozaru** [comment]
@Ippey プレビューではおかしかったのですが（タイミングかもです）
pull後、ローカルで確認したら問題なかったので

add-session-detail-about-rossブランチ、
コミット：d11961b

で良いと思います！ややこしくしてすみません。

**Comment by Ippey** [comment]
@kozaru ありがとうございます。
リリースにマージしちゃっていいですかね？

**Comment by kozaru** [comment]
@Ippey お願い致します！
