### ISSUE TITLE
公開時点でのNews

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#29]
@Ippey @pictron どうしましょうか？
https://megumilog.backlog.jp/view/DOJOCON-295

**Comment by kozaru** [comment]
@kwaka1208 
Newsは更新を広報チームで担当予定ですが、原稿は各チームで準備が前提だと思うので、原稿をおねがいしたいです。（杉山さん、それでよかったですよね？）

@pictron 
7/11エントリー開始のNewsを会場チームで書いていただけることになりました。
https://megumilog.backlog.jp/view/DOJOCON-408#comment-1142491452

Slackでいくつか書いてくださっている中に入っているようなら、若林さんに連絡をお願いします。その辺りの連携はお二方にお任せしていいですか？

プラス各記事ごとに写真があったほうが良いと思っています。写真を探す担当をどうするかなどは決まっていませんが、用意が難しい場合は、Newsの内容の合わせて連絡いただければ、デザインチームと相談します。

@Ippey 
Newsのエントリー作業、どうしましょうか？
説明等する時間がすぐには取れそうにないので、こちらで最初担当して公開後は運用も含めお願いする形でもよいですし、説明なくてもできそうなら、更新後プルリクエストを送っていただいてもよいです。ご希望をお聞かせください。

**Comment by kwaka1208** [comment]
@kozaru 
Newsの文字数上限、下限ってありましたでしょうか？これ以上無いと形になりにくいとか。

**Comment by kwaka1208** [comment]
@kozaru 練習を兼ねて、記事をコミットしました。カテゴリーとか決まってましたでしょうか？
@pictron @Ippey 内容の確認をお願いします。 m(_ _)m
http://dojocon-japan.github.io/jekyll/update/2016/06/12/entry_will_be_started_on_july_11th.html

**Comment by kozaru** [comment]
@kwaka1208 
記事の投稿フローは現時点で決まっていないので、上記のコミットをどうするかは、一旦保留にさせてください。

@Ippey 
記事の全体投稿フローどうされますか？
Issueでっておっしゃっていましたが、公開後だと思っていました。
申し訳ないですが、本日はその他の更新があり、上記を考えたり、みなさんにそれをシェアしたりという時間がありません。月曜日の夕方以降でしたら、Issueでの依頼をSlackに書いたようにみなさんにお知らせするという作業も可能です。
広報さんでやっていただいてもいいですし、今回の初回の記事投稿をどうするかも合わせて、お返事をいただければ助かります！

**Comment by kwaka1208** [comment]
@kozaru はい、それで結構です。

**Comment by kozaru** [comment]
@kwaka1208 masterブランチでの作業はしばらくやめてください。よろしくお願いします。

**Comment by kwaka1208** [comment]
@kozaru 了解しました、申し訳ありません。

**Comment by kozaru** [comment]
@ixkaito 
取り急ぎ連絡です。
Newsが１つ、masterブランチでpushされています。
今後の修正等については、一平さん（広報チーム）と相談後、作業予定です。また、masterブランチでの作業は、公開まではやめてくださいとおねがいしました。
全体にもmasterブランチでの作業はやめていただくように公開したほうがよければ、お知らせください（多分わかる方とそうでない方がいらっしゃるので、なくてもいいかなぁと思っています。）

**Comment by Ippey** [comment]
@kozaru 
記事の投稿はこちらで行います。
前回のミーティングで話し合った通り
1. 各チームがNews記事記載のISSUEを作ってもらう。（タイトル、草稿、公開日を指定してもらう）
2. 広報チームがMarkdownでファイル作成。レビュー用レポジトリにプルリク送る。
3. Webチームが問題なければ、レビュー用レポジトリにマージ。
4. 確認後、問題なければ広報チームが本番レポジトリにプルリク送る。
5. Webチームがマージ。

でいいと思います。
公開前にISSUEを立てるのが微妙であれば、その辺はSlackかBacklogでやりとりするようにしましょう。

**Comment by kozaru** [comment]
@Ippey 
もろもろありがとうございました。

## News掲載ルールの確認と告知

backlogのWebチームのWikiに書きました。ご確認ください。
みなさまへのご連絡は広報チームからやっていただいたほうがよいと思っていますので、よろしくお願いいたします。また、MarkDownファイル作成時にはブランチを切って行ってください。

今回公開の際は、手動でみなさまにご確認頂く予定なので、4.のプルリクは不要です。3.のあと各チームで確認をお願い致します。(#30 にて @tkc49 さんに確認済み）

公開時点のNews記事の確認がすべて終了しましたら、
このIssueで@ixkaito さんと私にお知らせいただければと思います。

## 公開時点でのNews記事

本日 @pictron が書いてくださっています。
Slackの広報チームチャンネルで6/10 の夜に記載されていました。
上記については、@pictron さんに確認をお願いいたします。

またそれとは別に @kwaka1208 さんが
 41511b5
にて記事を追加されていますので、合わせて確認をお願いします。

## Newsの実際の更新方法

各ページにサムネイル画像を一枚配置するレイアウトになっています。
- Markdownファイル追加場所
- Markdownの書き方
- サムネイル画像の選択（ない場合は Now Printing になりますがある方が良いと思っています）
- サムネイル画像他の加工方法
- サムネイル画像他の保存場所
- サムネイル画像のMarkDownへの記載方法

いずれかでご不明点や、Webチームで決めたほうがよいことがありますか？
また、本文内にも画像が必要なパターンがあれば、マークアップ方法を@ixkaito さんにお願いをしていただければ助かります。

上記以外にもご不明点がありましたら、お知らせください。
どうぞよろしくお願いいたします。

**Comment by ixkaito** [comment]
カテゴリーはいらないような気がしますので、一旦削除しました。
これは記事の URL に影響しますので、必要であれば予め決めておき、そのあとは変更しないほうがいいです。

あと、ファイル名（URL）は `_` （アンダースコア）ではなく、`-` （ハイフン）に統一するようにしました。

See #45

**Comment by kozaru** [comment]
@Ippey 
#49 プルリク分マージされています。
会場チームの画像が入っていません。こちらをPushしていただいた後、closeお願いします。

**Comment by Ippey** [comment]
@kozaru 
#89 プルリク送ってますー

**Comment by kozaru** [comment]
マージしました。Closeします。
