### ISSUE TITLE
公式サイトの公開への流れ確認

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#30]
https://megumilog.backlog.jp/view/DOJOCON-402#comment-1142485921

@ixkaito 準備でき次第となりますが、
1. 構築後のチェック
2. データの流し込み
   - Webチーム：データ差し込み
   - デザインチーム：写真選択/加工
   - 各担当チーム：原稿提出
3. 内容のチェック（ここ）
4. 公開

3.になったら、slackのgeneralで連絡、ある一定の時間を待って修正依頼がない場合＋関係各所にOKをもらった後、公開としたいのですが、それでよいですか？

---

slackのgeneral
Staff情報を公開していたり、そろそろ公開するよのお知らせも兼ねてした方が良いと思っています。

一定の時間
お昼間であれば、6時間くらい

関係各所
- 委員長
- 副実行委員長
- Web原稿担当チーム（広報・セッション・企画・デザイン・会場・スポンサーチームのWeb担当もしくはリーダー）

**Comment by kozaru** [comment]
@Ippey @tkc49 @kwaka1208 
委員長、副委員長に送っています。
上記の流れで、公開としたいと思っています。
確認にどれくらい時間がかかるかわかりませんが、間違った情報を流すよりは、情報を確認後がよいと思っています。
OKの場合、Reaction または、コメント、
ご意見ある場合、その内容をコメントおねがいしたいです。

**Comment by tkc49** [comment]
@kozaru はい、上記の流れでOKですー！
すぐに全部見れる時間がとれるかわからないですが、確認後GOの返事をいれます！

**Comment by kozaru** [comment]
では、その流れでお願い致します。
のちほど、BacklogのWikiに記載して、皆さんにお知らせします。

Closeします。
