### ISSUE TITLE
Workshop Lineの時間変更

### ISSUE THREAD

**Issue by asaga** [dojocon-japan/dojocon-japan.github.io#32]
「CoderDojo体験」と「大人のScratch教室」の開始時刻が10:40〜に変更になりました。（基調講演と同時スタート）
時間の区切りが変わりますので、修正をお願いしますm(_ _)m

修正前
　11:00-11:50, 12:00-12:50, 13:00-13:50, 14:00-14:50, 15:00-15:50

修正後
　10:40-11:30, 11:40-12:30, 12:40-13:30, 13:40-14:30, 14:40-15:30

**Comment by kozaru** [comment]
修正したのでcloseします。

**Comment by kozaru** [comment]
@asaga 問題あれば、お知らせくださいね。
