### ISSUE TITLE
Exhibitionに開始時刻を追加する

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#34]
https://megumilog.backlog.jp/view/DOJOCON-289#comment-1142493361

@asaga 
ワークショップ系は開始時間、それ以外は10時からでよいですか？

**Comment by asaga** [comment]
@kozaru 
はい、ワークショップは#32の通り、それ以外のExhibitionは10時スタートでお願いします。

**Comment by kozaru** [comment]
@asaga 修正後、マージしたのでcloseします。

**Comment by asaga** [comment]
ありがとうございました！
