### ISSUE TITLE
掲載写真追加

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#35]
Staff 寺園さん
Speaker 阿部先生

@akari-doi 
今後こんな感じで依頼したいのですが、よいですか？
スプレッドシートを見て加工が終わったら、こちらにコメントもらえたら、小寺が追加します。
https://drive.google.com/drive/folders/0B9m59ut-K_FzSkxnWTJyQXNqQ3c

**Comment by akari-doi** [comment]
@kozaru 
STAFF　寺園さん
Speaker　阿部先生
加工後指定フォルダへ入れました！

こちらで依頼いただいて大丈夫です。

**Comment by kozaru** [comment]
@akari-doi 追加ありがとうございました！closeします。
