### ISSUE TITLE
エントリーボタン非表示とエントリー開始時期のテキスト追加のおねがい

### ISSUE THREAD

**Issue by mayurin** [dojocon-japan/dojocon-japan.github.io#36]
https://megumilog.backlog.jp/view/DOJOCON-408#comment-1142491657
こちらの課題で、公開時にはエントリーボタン トルということになりそうです。
そこで小寺さんのご提案で、

> Entryボタンを非表示にして、
> Newsでその旨を書かれてはどうでしょうか？
> 
> プラスヘッダーには、7/11エントリー開始とテキストおいたらどうでしょう？
> 
> その場合、デザインも必要かもですが、カイトさんもデザイナーさんなのと時間リソースをかけすぎないために、テキスト表示はカイトさんにお任せしてはどうですか？

とありますが私も賛成です！
カイトさんお願いできますか？

お知らせに関しては若林さんが書いてくださっているみたいです。
http://dojocon-japan.github.io/jekyll/update/2016/06/12/entry_will_be_started_on_july_11th.html

**Comment by kozaru** [comment]
@mayurin
ありがとうございます。
#27とかぶってます。どうしましょう？

**Comment by mayurin** [comment]
未確認でした。ではこちらは止めましょう。
closeしますー @kozaru
