### ISSUE TITLE
Staff部分の追加・修正

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#38]
大野さん分お願いします。
細々ごめんなさい。

**Comment by akari-doi** [comment]
大野さん分完了しました！！

**Comment by kozaru** [comment]
@akari-doi ありがとうございます。
今プルリクでエラーがでていて、確認中なので、この画像追加したら、改めてこちらでお知らせします。

**Comment by kozaru** [comment]
@akari-doi 
ながとみさん分よろしくお願いいたします。

**Comment by kozaru** [comment]
@akari-doi 画像のファイル名の間に使っていた仕切り用の記号を `_` （アンダースコア）から `-` （ハイホン）に修正しました。その他のファイルがそうなっていたので...今までの分はこちらで修正します！

**Comment by akari-doi** [comment]
@kozaru ながとみさん分完了です！フォルダへ入れました！

**Comment by kozaru** [comment]
@ixkaito 
この時点で届いている分までは、プルリク出しています。

**Comment by kwaka1208** [comment]
池上さんは掲載無しで、お願いします。

**Comment by kozaru** [comment]
@kwaka1208 その他にも動きがありそうなので、もうちょっとまってから、まとめて修正しますね。

**Comment by kwaka1208** [comment]
はい、今何人かまとめてコンタクトしているので、また連絡します。

**Comment by kozaru** [comment]
@okhiroyuki 増減関連は、PDFも統一したほうがよいと思うので、ご招待しました。

**Comment by kozaru** [comment]
@kwaka1208 よろしくお願いいたします。

**Comment by kozaru** [comment]
@kwaka1208 
Googleドライブのコンテンツ内のアイコン用画像を見たのですが、追加がありませんでした。
https://drive.google.com/drive/folders/0Bx9lqWr1252eVUVtTGtGRGd5ZGc

なので、一旦森さんのURLのみ追加しました。

画像の加工は、土居さんに依頼しています。
大勢の方にお声をかけていただいているので、ある程度集まった段階でこのIssueのコメントでおねがいしてください。

また、URL含めその他の方の情報もその際に、ご依頼ください。よろしくお願いいたします。

**Comment by kwaka1208** [comment]
@kozaru 
取り急ぎ、現時点での状況をまとめます。
池上さん→削除
斉田さん→削除
森さん→念のため確認したら、加工済みフォルダに置いてはるようです。加工済みフォルダの画像を使ってください。
他の方も既読にはなっているので、近々反応があると思います。

**Comment by kozaru** [comment]
@akari-doi 
6/15 22時くらいの時点で、2枚画像が追加になりました。
まだ追加ありそうなので、あった場合は、それも含めて、あかりちゃんのタイミングのよいときに、加工をおねがいします。加工後、こちらに連絡をいれていただければ！と思います。

**Comment by kozaru** [comment]
@kwaka1208 画像の追加以外のここまでの修正をプレビューに反映しました。

**Comment by akari-doi** [comment]
@kozaru 森さんと酒井さん追加しました！表にも記載しました！

**Comment by kozaru** [comment]
@akari-doi 柴田さんの写真の加工をお願い致します。

**Comment by kozaru** [comment]
一旦ここまでの状態で、公開の準備に入りたいと思います。
@kwaka1208 問題あれば、コメントください。

**Comment by kwaka1208** [comment]
@kozaru いえ、ありません。よろくお願いします！

**Comment by mayurin** [comment]
@kozaru 柴田さん入れました。

**Comment by kozaru** [comment]
@mayurin ありがとうございます！

**Comment by mayurin** [comment]
@kozaru すみません、入れ直しました！

**Comment by kozaru** [comment]
@kwaka1208 こちら公開まで分の追加が終了したので、一旦Closeしますね。
アイコン画像の追加などは、随時Issueなどでお知らせいただければと思います。
