### ISSUE TITLE
Exhibition 写真追加

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#40]
パーラービーズ、依頼中です。

@akari-doi 
パーラービーズ以外、写真できたら、こちらでお知らせお願いします。

**Comment by kozaru** [comment]
@akari-doi 
@mayurin 
Googleドライブの加工後の写真置き場に、パーラービーズの写真を入れました。
加工よろしくお願いします。
今回どちらがされるかわかんなかったので二人にメンション入れておきますね！

**Comment by akari-doi** [comment]
@kozaru 完了しました！よろしくお願いいたします！

**Comment by kozaru** [comment]
@ixkaito 
プルリク出しています。
