### ISSUE TITLE
【一般公開までに】OGP画像の追加

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#41]
チケットもありますが、こちらにも載せておきますね。

**Comment by kozaru** [comment]
@mayurin どんな感じでしょうか？

**Comment by mayurin** [comment]
@kozaru @tkc49 細谷さんのキャッチコピーを含めるフィードバック待ちというところです。
https://megumilog.backlog.jp/view/DOJOCON-321
また、キャッチコピーが決まれば以下、ベンディング中の課題もすすめることができます。
チラシデザイン
https://megumilog.backlog.jp/view/DOJOCON-164
FacebookとTwitterのカバー画像デザイン
https://megumilog.backlog.jp/view/DOJOCON-332

**Comment by kozaru** [comment]
@tkc49 
ご招待しておきますね。細谷さんがキーマンな雰囲気を感じ取ったので。

**Comment by mayurin** [comment]
https://drive.google.com/file/d/0B-O-Ui4qJxjLUnhXNUtqaVVOV1k/view?usp=sharing
@kozaru @ixkaito  お待たせしました。こちらにOGPデータをアップいたしました。
よろしくお願いします！

**Comment by ixkaito** [comment]
@mayurin
ありがとうございます！
