### ISSUE TITLE
サイト更新時の注意事項（随時追加）

### ISSUE THREAD

**Issue by ixkaito** [dojocon-japan/dojocon-japan.github.io#44]
@okhiroyuki @Ippey @pictron @kwaka1208 @kozaru @tkc49 @mayurin @michieymt @tajuta @akari-doi @asaga 
- 基本的には直接プッシュではなく、プルリクしてください。マージはテストをパスしたあとご自身でやってもいいですし、心配なようであればそのままにしてもらえればマージします。
- サイト内のページやアセット（画像など）へのリンクは、からなず `site.baseurl` を `prepend` してください。例：
  - ホームへのリンク： `{{ '/' | prepend: site.baseurl }}`
  - イメージフォルダ coderdojo-logo.svg へのリンク： `{{ '/assets/images/coderdojo-logo.jpg' | prepend: site.baseurl }}`
  
  今回のサイトではおそらく大丈夫ではありますが、万が一サイトごとサブディレクトリに入る場合、`site.baseurl` がないとリンク切れになります。 

今後気づいたことがあったら随時追加します。

**Comment by kozaru** [comment]
イメージフォルダ coderdojo-logo.svg へのリンク 6/13夕方頃に修正して連絡します。

**Comment by kozaru** [comment]
@ixkaito @Ippey 
以下、修正後追記しました。6/13 18:48
以下、表記を統一しました。6/13 18:56
- トップページを変更する場合
  - localでNode.js/Rubyの環境を使って表示の確認をしてください。
  - cssの調整が必要な場合は、一旦Webチームに打診をしてください。
  
  上記が難しい場合は、Issueで依頼してください。
- 画像を追加する場合
  - Node.js は必要、Ruby (Jekyll) は不要。
  - 画像ファイル保存ディレクトリ`/assets/_images/`に保存します。
  - 圧縮 (`npm run imagemin`) 後プルリクエストしてください。
  
  上記が難しい場合は、Issueで依頼してください。
- Newsのマージ
  - 新規記事のときのその記事の `External link` エラーは無視してマージしてください。

**Comment by kozaru** [comment]
@Ippey 
#29より以下、追記しました。6/14
- News記事のファイル名
  ファイル名（URL）は _ （アンダースコア）ではなく、- （ハイフン）に統一するようにしました。

**Comment by Ippey** [comment]
あれ？
アンダースコア入ってました？
すいません。。

**Comment by kozaru** [comment]
@Ippey 入ってないです。ここに、注意事項を並べています。

**Comment by kozaru** [comment]
#115

### 本番リポジトリへのマージ

`master`→`release`のマージは、Webチーム / 広報News担当にて
1. `master` ブランチ上ですべての確認を完了させる
2. `release`ブランチに対してプルリクを送る
3. 2のプルリクがマージすればしばらくしたら本番に反映

### プレビューで他のチーム等への確認が必要な場合
1. それぞれのブランチ→ `master` にマージ
2. 担当者にプレビューOKかどうかの確認（※1 ※2）
3. `release` にマージ

**Comment by kozaru** [comment]
@Ippey 
jekyll Markdown 内でのリンク target="_blank"の設定
該当部分のみ、タグで記載してください。

``` md
テキスト<a href="https://github.com/" target="_blank">GitHub</a>テキスト
```

参考：[markdown target=“_blank”](http://stackoverflow.com/questions/4425198/markdown-target-blank)

**Comment by ixkaito** [comment]
デフォルトブランチを master から release に変更しました。（プレビューされるのは今までどおり master、リリースするときのプルリクも今までどおり base: release / compare: master）

この変更により、release でマージするときに、コミットメッセージに "fix #0" のように、"fix" などの後ろに issue 番号を入れておくと、本番へ公開するタイミングで自動的に issue を close できるようになりました。
