### ISSUE TITLE
Sponsor申し込みへのリンク

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#5]
@ixkaito 別ページにリンクになると思うのですが、どのページか教えてもらえると助かります。

以前、URLの問題があったので、ティーザーサイト同様同じURL内での表記がよいのではと思っています。

**Comment by ixkaito** [comment]
@kozaru これは普通に Google Form に飛ばすのではないんですかね？

**Comment by kozaru** [comment]
@ixkaito 
スポンサー申し込みフォーム、URLをDojoConにしたいというご希望がでています。
可能かどうかについては、これからの検討となります。とお返事しています。

@okhiroyuki 
@tkc49 
Issue遅くなりました。こちらで話し合いましょう。

**Comment by ixkaito** [comment]
@kozaru @okhiroyuki @tkc49 
DojoCon の URL でも大丈夫ですよ。下記の方法がありますのでご検討ください。
- フォームのシングルページ
- スピーカーのようなモーダルウィンドウ
- ボタンの下に現れる

**Comment by okhiroyuki** [comment]
自分は、シングルページがいいかな。

**Comment by tkc49** [comment]
同じくシングルページが良いです！！！
