### ISSUE TITLE
Exhibition height css のレスポンシブ対応

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#52]
PCのみの設定しか書いていなかったので、レスポンシブ対応に書き直す。

**Comment by kozaru** [comment]
@ixkaito 
プルリク出しています。css問題あれば、修正してください。

**Comment by ixkaito** [comment]
@kozaru 
CSS でレスポンシブ対応がややこしそうなのであとで JS で対応します。

**Comment by kozaru** [comment]
@ixkaito 
よろしくお願いします！
