### ISSUE TITLE
写真提供表記を追加：パーラービーズ

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#58]
写真提供表記を追加する

今後も写真提供いただいている場合は追加予定。
https://megumilog.backlog.jp/view/DOJOCON-379

**Comment by kozaru** [comment]
@ixkaito 近岡さんには、キャプチャで確認していただきました。良き案あれば、修正していただければと思います。

**Comment by ixkaito** [comment]
Fixed. See 6bcc51f
