### ISSUE TITLE
開催概要の予定時刻

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#59]
開催日 : 2016年8月27日（土）
時間 : 10:40 - 13010（予定）

となっているとご指摘をいただいて、正確な開始時間・終了時間の記載はどうしたらよいのか教えてほしいです。

担当がわからなかったので、セッション・企画・広報・会場＋細谷さんにAssigneesしました。

**Comment by kwaka1208** [comment]
10:00　開場
10:30　開始
16:30　全セッション終了

なので、
10:30-16:30（開場 10:00）
としたいと思いますが、いかがですか？10:00開始だとそれまでに来られる方が多数でられるかもしれないので、開場時刻を明確にした方がいいかなと思いました。

**Comment by kozaru** [comment]
@kwaka1208
上記で入力しておきますので、修正あれば連絡ください。

**Comment by kwaka1208** [comment]
はい、それでお願いします。

**Comment by kozaru** [comment]
変更したのでCloseします。
