### ISSUE TITLE
Speakerの掲載順序

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#65]
@tkc49 を追加しました。
掲載順をご確認お願いします。
問題なければ、Closeしてください。

**Comment by Ippey** [comment]
掲載順ですが、お手数ですが
1. CoderDojo部外者（＝阿部さん、他）
2. CoderDojoFoundation（=ROSSさん）
3. CoderDojo関係者で実行委員外（＝宮島さん、東さん）
4. 実行委員
の順でお願いできますでしょうか？

**Comment by kozaru** [comment]
修正しましたのでCloseします。
コンテンツ関連のことなので、Issueの注意事項（システム周りのことが書いてあります）ではなく、Backlog・60_サイト制作 Wiki に追記しておきました。
