### ISSUE TITLE
Exhibitionの文字修正

### ISSUE THREAD

**Issue by asaga** [dojocon-japan/dojocon-japan.github.io#66]
Touch&Try／BlocklyDuino
→ BlocklyDuinoで電子工作体験（Touch&Try）

パーラービーズ
→パーラービーズでドット絵体験

に修正頂いて良いでしょうか。

**Comment by kozaru** [comment]
修正しました。
Closeします。

**Comment by asaga** [comment]
ありがとうございましたm(_ _)m
