### ISSUE TITLE
公開時点のStaff情報

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#69]
写真未着の場合は現在（6/15）時点のプレビューに表示されているダミーアイコンを使用する予定です。

問題有りましたら、ご意見くださいませ！

**Comment by kozaru** [comment]
@okhiroyuki 増減関連は、PDFも統一したほうがよいと思うので、ご招待しました。

**Comment by kozaru** [comment]
@Ippey @kwaka1208 @tkc49 
今のところ、ご意見ないようなので、公開までに画像を用意できない場合は、ダミーアイコンで行こうと思っています。しばらくお返事なければ、クローズしますね。

**Comment by kwaka1208** [comment]
はい、私はそれでいいと思います。

**Comment by kozaru** [comment]
@kwaka1208 ありがとうございます。

お返事無いようなので、今のまま行きたいと思います。Closeしますね。
