### ISSUE TITLE
とがぞのさんのプロフィール＆セッション概要変更依頼

### ISSUE THREAD

**Issue by Ippey** [dojocon-japan/dojocon-japan.github.io#70]
セッション概要をいただきました。
あわせて、紹介文をへんこうされましたので、差し替えお願いします。

[紹介文]
CoderDojo Kodairaの代表で近隣Dojoのメンター。大学を卒業後、公共サービス系システムのエンジニアとして数年従事。幾つかの雇用形態で職を転々とした後、2年間引きこもり生活を実践。世の中にはびこる「当たり前」の真偽に興味を持ち、あれやこれやと仮説立て・実践・検証を繰り返すうちに数年経過。「武蔵野・多摩地域を時々徘徊する素浪人」なる立ち位置を確立させようと日々邁進しつつ「地域xITx教育」をキーワードにK-12教育の現場に爪足を突っ込んで現在に至る。趣味は生きること。しようもないものづくりも好き。手先と人間性が非常に不器用。好きな言葉は「試行錯誤」と「スクラップ・アンド・ビルド」。

[セッション概要]
CoderDojo Kodairaは2014年に発足しました。発足3ヶ月足らずで活動を休止し、9ヶ月後に再開して現在に至ります。コンピュータサイエンスやテクノロジーアートとは縁遠い人達にこそ新しい場を開きたくて、敢えて活動に共感する仲間が殆どいないプチ田舎で活動しています。
「放課後の居場所のひとつ」を目指して平日夕方に開催している点や、保護者に「もっと安価にPCを入手する方法を知って欲しい」とバルク品のPCを再利用している点など、お節介心が勢い余って「なんでそんな手間で面倒なことを…」と傍目に思われるような方向から攻めている部分を紹介できたらと思います。

**Comment by kozaru** [comment]
@Ippey 
ありがとうございます！
Staff周りの変更依頼を待って、合わせて修正でもよいですか？
また、上記以外にも公開までの修正がありそうですか？

**Comment by kozaru** [comment]
@Ippey 
追加しました。
一名追加分はこれとは別だと思うので、情報揃ったら、Issueお願いします。

@ixkaito 
- セッションのポップアップのスピーカーアイコンから、スピーカーのポップアップへのリンクを貼りました。
- スピーカーのポップアップのセッションテキストから、セッションのポップアップへのリンクを貼って、リンク用のスタイルを設定しました。

作動には問題ないようでしたが、あればお知らせください。
このほうが使いやすいと思ったのですが、そのあたりもご意見あれば、教えてください。
上記問題なければ、CLOSEお願いします。

**Comment by kozaru** [comment]
@ixkaito TimeTableのポップアップからは、 Speakerの名前テキストからもリンクした方がよいかもですね。作動に問題なければ、その他の作業のときに追加しますね。

**Comment by ixkaito** [comment]
@kozaru 
問題ないと思います。そうですね、スピーカーの名前からもリンクしてもいいかも。
ちなみに、ポップアップ内のリンクの `rel` 属性は削除した方がです。左右ボタンでそれも回してしまうので。

**Comment by kozaru** [comment]
@ixkaito 
`rel`の追加、jsでやってはるようなんですが、js書き換えてもいいですか？

**Comment by ixkaito** [comment]
@kozaru 
そういえば。この件は対応します。

**Comment by ixkaito** [comment]
@kozaru 
ポップアップの挙動を修正しました。See a61a2ac

@Ippey 
テキストが問題なければ close して大丈夫です。

**Comment by kozaru** [comment]
@ixkaito 
午後から、スピーカーの名前からリンクも追加しておきます。（別Issue立てます　#80）

@Ippey 
このIssue、テキスト確認後、Closeお願いします。

**Comment by Ippey** [comment]
確認しました。ありがとうございます。
