### ISSUE TITLE
公開時点でのHTMLコメントアウト

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#71]
相談です。
いくつか、コメントアウトで残していますが、公開時点では取った方よいでしょうか？
取る方向なら、ブランチで残そうと思っています。
ご意見いただければ、うれしいです。

**Comment by ixkaito** [comment]
@kozaru 
取る必要はないです。
ビルド後のソースではコメントは自動的に削除され、HTMLも圧縮されます。
サイト開いてソース確認してみてください。
Close しますね。

**Comment by kozaru** [comment]
ありがとうございました！
