### ISSUE TITLE
「CoderDojoとは？」のDojo数の記載変更

### ISSUE THREAD

**Issue by kwaka1208** [dojocon-japan/dojocon-japan.github.io#74]
急ぎではありませんが、Dojoが1,000を超えているのとRossさんのセッションのタイトルに「1,000」という数字が出ているので、「CoderDojoとは？」のDojo数の記載変更を提案します。
あと、「段階」よりも「時点」の方が自然かなと思いました。

変更前：Dojoの数は世界中で970（2016年5月段階）にも及びます。
変更後：Dojoの数は世界中で1,000（2016年6月時点）にも及びます。

**Comment by kozaru** [comment]
@pictron いかがでしょうか？
@kwaka1208 決定したら、メンション入れて連絡いただければ助かります。

よろしくお願いいたします。

**Comment by pictron** [comment]
@kozaru @kwaka1208 特にずっと数字を変えるのもどうかと思い、意図して修正しませんでした。（もう1000でもなかったりしたので）、余裕があれば変えていただいてもいいですが、私の中ではプライオリティは高くありません。

**Comment by ixkaito** [comment]
@kwaka1208 @pictron 
「Dojoの数は世界中で1,000以上にも及びます。」でどうですか？

**Comment by kwaka1208** [comment]
@ixkaito はい、それでいいと思います。ありがとうございます。
