### ISSUE TITLE
「CoderDojo小平の活動内容」それとも「CoderDojo Kodairaの活動について」？

### ISSUE THREAD

**Issue by ixkaito** [dojocon-japan/dojocon-japan.github.io#76]
@kozaru 
セッションタイトルが記載場所によって違いますが、どちらが正しいでしょうか？

**Comment by kozaru** [comment]
@ixkaito すみません。
CoderDojo Kodairaの活動について
が正しいです。
修正してプルリク送ったほうがいいですか？

**Comment by kozaru** [comment]
dev-ko ブランチでpushしておきましたので、修正しやすいようにしてください。

**Comment by ixkaito** [comment]
マージして close して大丈夫です。

**Comment by kozaru** [comment]
マージしました。
