### ISSUE TITLE
Scratch の文言を追加

### ISSUE THREAD

**Issue by ixkaito** [dojocon-japan/dojocon-japan.github.io#8]
Scratch のコピーライト的なものをフッターあたりに追加。

**Comment by ixkaito** [comment]
@akari-doi @mayurin 
すみません、これの正しい文言をもう一度教えてもらえますか？

**Comment by akari-doi** [comment]
@ixkaito 遅くなりすみません！

[利用しているScratchのブロック画像]
CC BY-SA 2.0 / Scratch is developed by the Lifelong Kindergarten Group at the MIT Media Lab. See http://scratch.mit.edu.

です！

**Comment by mayurin** [comment]
@ixkaito @akari-doi  すみません、Githubに慣れてなくて諸々Issuesを確認してこちら気になったので。
 [利用しているScratchのブロック画像] CC BY-SA 2.0
↓
 [利用しているScratchの画像] CC BY-SA 2.0
の方が幅が出ていいかなと思うのですがどうでしょう。
