### ISSUE TITLE
公開時点のセッション・スピーカー周りの情報のFix

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#83]
公式サイト公開時点での内容を決めていきましょう

**Comment by kozaru** [comment]
@Ippey 今の状況でOKのようでしたら、その旨ご連絡ください。
追加・修正等のご希望がある場合も、その旨ご連絡いただければと思います。
よろしくお願い致します。

**Comment by Ippey** [comment]
石原さんの情報を追加しましたので
こちらの追加をお願いします。
これで公開時点はfixでよいです。
残りはもらい次第issueを投げます。

**Comment by kozaru** [comment]
@Ippey ありがとうございます。承知しました。上記反映後、このIssueクローズして、内容確認用のIssueを立てます。よろしくお願いいたします。

**Comment by kozaru** [comment]
@Ippey
石原さんのWeb掲載用の画像、高解像度のものがないでしょうか？
掲載予定サイズが400px x 400px になります。
頂いている画像が73px x 73px になっています。

@akari-doi 
上記確認後、加工をおねがいしたいです。

**Comment by kozaru** [comment]
@ixkaito 
Speakerポップアップにgithubへのリンクアイコンの作成おねがいできますか？
URLは別途送っていただいているので、デスクトップのアイコンは併用できないです。

↑
追記・一旦上記の依頼取り消します。お騒がせしました。

**Comment by kozaru** [comment]
@akari-doi 石原さんの写真よろしくお願いいたします。

**Comment by kozaru** [comment]
@akari-doi 写真が比較的綺麗だったので、リサイズのみして、掲載しました。
加工していただいたら、差し替えるので、連絡いただければと思います！

**Comment by mayurin** [comment]
https://drive.google.com/file/d/0B-O-Ui4qJxjLLXR5czEwYzFteW8/view?usp=sharing
これもう間に合ってます？

**Comment by kozaru** [comment]
@mayurin ありがとう！jpgでおねがいしてもいいですか？写真アイコンはjpgにしています。

**Comment by mayurin** [comment]
了解です！

**Comment by mayurin** [comment]
@kozaru 石原さん入れました。

**Comment by kozaru** [comment]
@mayurin ありがとうございます

**Comment by kozaru** [comment]
上記追加したのでCloseします。
