### ISSUE TITLE
Exhibitionへの追加

### ISSUE THREAD

**Issue by asaga** [dojocon-japan/dojocon-japan.github.io#84]
以下の内容で追加をお願いします。

---

タイトル：
MR（混合現実）体験！Oculus Riftを使ってバーチャルドローンを飛ばしてみよう！

掲載文言：
MR（Mixed Reality：混合現実）とは ＝ VR（バーチャルリアリティ）と現実との混合の世界。
VRゴーグル（Oculus Rift）に取り付けた立体カメラから取り込まれた実風景に、CGで作られたドローンをリアルタイムで合成。VRゴーグルの中のバーチャルドローンをゲームパッドで操縦してみよう！（対象年齢：13歳以上）（協力：株式会社XOOMS(ズームス））

掲載画像：
XOOMSさまで作成中→公開に間に合わなければ、NowPrintingとしてください。

**Comment by kozaru** [comment]
@asaga 掲載順は、パーラービーズの後にする予定ですが、全体を含めて、掲載順確認おねがいしたいです。

**Comment by kozaru** [comment]
@asaga 追加したのでCloseします。

**Comment by kozaru** [comment]
写真や修正等あれば、改めて連絡ください。
