### ISSUE TITLE
セッション概要　学生の道場運営者に聞く！

### ISSUE THREAD

**Issue by Ippey** [dojocon-japan/dojocon-japan.github.io#86]
対応は、公式サイトオープン後で良いです。

タイトル：
学生の道場運営者に聞く！

概要：
CoderDojoはいろいろな人が運営していますが、社会人ではなく学生の方が運営している道場もあります。
そんな学生運営者のCoderDojo柏　宮島さんとCoderDojo明石　東さんにCoderDojoの運営をしてみようと思った経緯や運営についての苦労話、自分の学業への影響など、ざっくばらんにお話をうかがいます。

**Comment by kozaru** [comment]
@Ippey 追加したのでCloseします。
公式サイトオープンに入れました。
