### ISSUE TITLE
【セッションのみ追加】有償と無償で何が違う？ プログラミング教室/コミュニティー運営座談会

### ISSUE THREAD

**Issue by Ippey** [dojocon-japan/dojocon-japan.github.io#87]
対応は公式サイトオープン後で良いです。

タイトル：
有償と無償で何が違う？
プログラミング教室/コミュニティー運営座談会

概要：
文部科学省から発表された『2020年から小学校のプログラミング必修化』を受け、各地でプログラミング教室が設立されています。
CoderDojoのような無料のプログラミング教室と何がちがうのか、プログラミング必修化を受けて、今後どのように活動していくかなどを
有償プログラミング教室からTENTO　谷岡様、CoderDojoから橋爪さんにお話をうかがいます。

**Comment by kozaru** [comment]
こちらは、公開後に確認して掲載したいと思います。

**Comment by kozaru** [comment]
@Ippey 

セッション：有償と無償で何が違う？
プログラミング教室/コミュニティー運営座談会

スピーカー：TENTO　谷岡様
CoderDojoから橋爪さん

かなと思ってます。谷岡さんの解像度高い画像と、橋爪さんの情報が揃ったら、教えてください。追加します。スピーカー情報が揃う前に、セッション情報のみの追加をご依頼の場合は、その旨お知らせください！よろしくお願いいたします。

**Comment by kozaru** [comment]
@Ippey こちらどんな感じでしょうか？
情報が揃わない等であれば、一旦Closeして、再度オープンでもいいですし、セッションのみ先にアップであれば、そうしますので、お知らせいただければ助かります。

**Comment by Ippey** [comment]
二人には週末に情報を依頼していますが、まだ返事が返ってきていません。
セッションのみ先にオープン出来るのであればその方向でお願いします。

**Comment by kozaru** [comment]
@Ippey では、最初セッションのみですすめますね。
Issue タイトル変更します。

**Comment by kozaru** [comment]
依頼が公開後の場合、Speakerさんは他にIssueを立てていただければと思います。

**Comment by kozaru** [comment]
@Ippey 橋爪さんのフルネーム分かりますか？
わからない場合、谷岡さんのみスピーカーとして掲載されますか？あるいはスピーカーは掲載なしにしますか？

**Comment by Ippey** [comment]
@kozaru 
はしづめ　かおり　さん
なのはわかっているのですが、漢字がわからないです。
なので、谷岡さんのみスピーカーとして掲載してください。

**Comment by kozaru** [comment]
@Ippey 文章はそのまま掲載しますね。

**Comment by kozaru** [comment]
@Ippey プレビューに反映されました。
@ixkaito 本番へのマージおねがいします。

**Comment by kozaru** [comment]
@ixkaito 確認を忘れていました。マージお待ち下さい。
@Ippey 確認後OKの場合、本番へのマージ依頼という流れで良いですか？

この辺の流れも決めたいですね。

**Comment by kozaru** [comment]
@ixkaito マージしていただきありがとうございました。
@Ippey 確認ありがとうございました。

Closeします。
