### ISSUE TITLE
公式サイト公開用チェック

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#91]
#### 3. コンテンツ担当チームのみなさまは、確認が終わりましたら、コメントいただければと思います。

コンテンツ担当チーム
- [x] 広報チーム：杉山さん [全体/News/Aboutテキスト/Contactフォーム]
- [x] セッションチーム：一平さん（リーダー：高坂さん）[Speaker/TimeTableセッション部分]
- [x] スポンサーチーム：岡田さん [Sponsors/PDF/申込フォーム/行動規範]
- [x] 企画チーム：浅賀さん [TimeTableワークショップ部分/Exhibition]
- [x] 会場チーム：若林さん [Access/Entry周り]
#### 4. Webサイト制作チームのみなさまも最終確認をお願いします。

Webサイト制作チーム
- [x] デザインチーム：近岡さん [デザイン全般]
- [x] Webチーム：カイトさん [コーディング・構築全般]
#### 5. 3. 4. 終了後、実行委員長最終確認

最終確認
- [x] 委員長：細谷さん [全体]
#### 6. 公開

公開日時、シェアや公開リポジトリへのマージ等で調整をおねがいしたいです。
広報シェア：@pictron / @Ippey （副委員長の一平さんも一緒に調整お願いできればと助かります）
公開リポジトリへのマージ：@ixkaito

**Comment by kwaka1208** [comment]
確認しました、OKです。

**Comment by pictron** [comment]
マストな修正はありません。
１つだけ「とがぞの」さんは、このテストページ見てるのかな？1人だけイラストが逆に違和感がありますね。

**Comment by asaga** [comment]
Exhibitionのレイアウト（余白が多い）を修正したいと思っていますが、後回しでも大丈夫なので、ひとまず現状でOKです

**Comment by Ippey** [comment]
@kozaru , @ixkaito 
確認しました。
公開日時（本番レポジトリへのマージ）日時は追ってissueを立てます。
こちらのissueはプレビュー側のレポジトリで良いでしょうか？

@tkc49 , @kwaka1208 , @pictron 
公開後のシェアについては、ぼくからSlackへゴーサイン出そうとおもいます。
よろしいでしょうか？

**Comment by mayurin** [comment]
@Ippey できたら、Facebookとtwitterのアイコン、カバー画像、OGP画像、を入れ替えてからシェアしてもらえればと思います。
もし、キャッチコピーが間に合わないようであれば、取り急ぎはキャッチコピーがないバージョンの作成もありだと思います。現状はティザーのままなので。

**Comment by kwaka1208** [comment]
@Ippey 了解です！

**Comment by Ippey** [comment]
@mayurin 
了解です。
FBアイコン、Twitterのアイコンを切り替えたタイミングにします。
切り替えたらご連絡お願いします。

OGPに関しては、サイト公開時に変わるものだと思ってますがその認識でOKでしょうか？

あと、キャッチコピーが間に合わない〜というのはどこに使うキャッチコピーでしょうか？

**Comment by Ippey** [comment]
@mayurin 
自己解決しました。
これのことですか？

#41

**Comment by mayurin** [comment]
@Ippey そうです！
`切り替えたらご連絡お願いします。`
承知しました。

**Comment by kozaru** [comment]
@Ippey 良いと思います。よろしくお願いいたします。

> 公開日時（本番レポジトリへのマージ）日時は追ってissueを立てます。
> こちらのissueはプレビュー側のレポジトリで良いでしょうか？

**Comment by kozaru** [comment]
@tkc49 
大体のコンテンツの内容の確認ができました。
あとは
- OGP画像
- NowPrintingの差し替え
- #92 タイトルの表記
  くらいかと。そろそろ確認いただいてもよいのではと思っています。

また、Slackのスレッドになりますが、高坂さんが、Rossさんに確認をされています。

**Comment by kozaru** [comment]
@ixkaito 
@mayurin 
デザインやコーディング周りのチェックも一度お願いします。

**Comment by mayurin** [comment]
@kozaru OKです。

**Comment by ixkaito** [comment]
@Ippey 
issue はこちらのリポジトリで大丈夫です。公式サイト公開後は、あちらのリポジトリは公開用のみにして issue は無効化する予定です。

**Comment by ixkaito** [comment]
@asaga 
Masonry 風のレイアウトにするかですかね…
http://masonry.desandro.com/

もしくは、行毎に高さ合わせることはできるかもしれません。

**Comment by asaga** [comment]
@ixkaito 
そういうレイアウトもあるんですね…。
文字数に影響されないレイアウトができるのであれば嬉しいですが、今のところ問題になってるのがドローンの文章だけなので、文章を短くするのでも良いと思います。
今、永富さんとやり取りしてるところです。
https://megumilog.backlog.jp/view/DOJOCON-370#comment-1142872052

**Comment by kozaru** [comment]
@asaga チケットみました（おそくなってすみません）。文字数、短くするようなら、こちらにご連絡いただければと思います。

**Comment by kozaru** [comment]
@Ippey @tkc49 
高坂さんが、Slackで英語表記についてご連絡くださいました。

> サイト確認しました。私はGitHubのアカウント持ってないのでここでコメントさせてください。トップページの登壇者の紹介部分（写真＆名前）のところで、東さんの英語名だけHIGASHI, Kazukiとファミリーネームが先に来て大文字になっているところが結構気になりました。論文の名前の表記のようなスタイルですよね。ご本人が提供された表記だとは思いますが、できたら他の方と統一してKazuki Higashiとしたほうが見た目に良いと思いました。

上記のように修正してもよいですか？東さんに確認した方がよいですか？その場合、一平さん確認お願いできますか？

Issue立てておきます。混ざっちゃいそうなので。
#97

**Comment by kozaru** [comment]
@ixkaito 
ドローンはテキストを少なくする方向で動いてくださっています。
上記に書いてありますが、念のため、連絡です。チケット内で @asaga に確認しました。
https://megumilog.backlog.jp/view/DOJOCON-370#comment-1142872052

**Comment by kozaru** [comment]
@ixkaito 
Exhibitionの余白、テキスト差し替えでよくなりました！よかったです！
@asaga 
早々のご対応ありがとうございました！

**Comment by asaga** [comment]
だいぶよくなりましたね。
お手数おかけしましたm(_ _)m

**Comment by kozaru** [comment]
今みなさんのチェックに気づきました。
ありがとうございました！

残っているタスクは以下のとおりです。
- OGP追加
- #92 内のExhibitionテキスト修正
- ~~ロスさんへの確認 ※~~

~~※ Slack/session channel で高坂さんより（画像キャプチャで確認してもらっています）
今回チェックするウェブサイトについて、事前にRossに自分の箇所を見てもらっても良いですか？現在彼は休暇中なのでリーチできるかわからないんですけど。~~
ロスさんにお返事を待てないことお伝え頂けているということなので、上記削除しました（6/17 19:33）

上記が全部入った後、generalでお願いしようと思っていましたが、週末で連絡等が遅くなりそうなので、

@tkc49 最終確認に入っていただいて良い段階ではと思っています。よろしくお願いいたします。

@Ippey @ixkaito @pictron 細谷さんのGoサインに合わせて、公開日程の調整もお願いできればと思います。

@ixkaito テキスト修正やOGP画像の追加、気づいたらやりますが、PCの前を離れることが週末多いので、レスポンスが無いときはお願いできれば、助かります。

みなさま、ご確認等ありがとうございました！あと少しですね。公開が楽しみです！引き続き、どうぞよろしくお願いいたします。

**Comment by tkc49** [comment]
@kozaru はい！明日確認の時間とれると思います！

**Comment by kozaru** [comment]
@tkc49 よろしくお願いいたします！
週末で修正対応できそうなのは、土曜日曜ともに午前中になります。

**Comment by kozaru** [comment]
ロスさんの確認の件、変更しました。

**Comment by tkc49** [comment]
@kozaru 確認しました。気になったところをIssue立ててます！
#103 #104 #105 

#106 は優先度低めです。

**Comment by kozaru** [comment]
@tkc49 ありがとうございました！
本日今から予定があって、修正が明日の朝になります。
でき次第ご連絡しますね。どうぞよろしくお願いいたします。
（お姑さんとの会食で...時間厳守なのです...すみません）
また、先ほど高坂さんから連絡をいただき、ロスさんのプロフィールに英語表記を追加しています。
ご確認お願いできればと思います。

@ixkaito 可能でしたら対応お願いしたいです。#103 #104 #105 #106

@Ippey @ixkaito @pictron 細谷さんのOKがでましたので、公開日時の調整に入ってください。
よろしくお願いいたします。

**Comment by pictron** [comment]
@Ippey @asaga @tkc49 さん公開日時slackのgeneralに書きます。

**Comment by kozaru** [comment]
@tkc49 あと、OGPお願いします。#41

**Comment by kozaru** [comment]
@ixkaito ありがとうございました。

**Comment by kozaru** [comment]
@ixkaito あとOGP画像の追加で公開までの更新は終了かなと思っています。#41
公開されたら、このチケットcloseしますね。

**Comment by kozaru** [comment]
サイト公開されましたのでCloseします。
