### ISSUE TITLE
英語のタイトルに日本語表記が欲しい

### ISSUE THREAD

**Issue by tkc49** [dojocon-japan/dojocon-japan.github.io#92]
Sessions：セッション
Workshops：ワークショップ
Exhibition：展示 / 体験

かな？セッションとワークショップってそのままカタカナにしただけやけど・・・

**Comment by kozaru** [comment]
@pictron 入れる方向でいくとして
@mayurin デザインどれくらいかかりそうですか？

カイトさんにも見ていただいたほうがよくないですか？
（多分コーディングはカイトさんに...お願いすると思います）
Asigneesしておきますね。

**Comment by mayurin** [comment]
@kozaru 今から取りかかれます。1時間くらいでしょうか。

**Comment by tkc49** [comment]
英語のタイトルの下に日本語の表記もいれて頂ければ。
他の見出しもそうなので^^

**Comment by pictron** [comment]
@tkc49 うーん、いりますかね？
個人的には下に書いてある内容を見ればだいたいわかるので不要かと。
そこに入れても目が行かんのですよね

**Comment by tkc49** [comment]
@pictron そうですか(^^;)
セッションとワークショップは分かったのですが、
Exhibitionって意味がよく分からなくて、ググったのでｗ

**Comment by mayurin** [comment]
https://drive.google.com/folderview?id=0B-O-Ui4qJxjLMUhVazlTazBpdWM&usp=sharing
こちらにデータを入れました。縦にすると間延びすると思うので、横に添えた。という感じです。
![default](https://cloud.githubusercontent.com/assets/3609039/16114203/0340fe2e-33fb-11e6-93f7-bca8538d6292.png)

**Comment by mayurin** [comment]
![dojoconjapancs6-01](https://cloud.githubusercontent.com/assets/3609039/16114406/0c0c36f8-33fc-11e6-9b65-fcd278823ce7.png)
入れたイメージです。
カイトさんの方でいい案があればいい感じにしてもらってもOKです。

**Comment by Ippey** [comment]
@ixkaito 
ソースぱっと見ですが、文字の大きさを変えるのは結構手間だと感じましたが
いけますか？

**Comment by pictron** [comment]
うーん、展示 / 体験ってタイトルつけても圧倒的にわかりやすくなるわけじゃないので、下の文章できちんと説明したほうがいいのでは？
下の文章がわりかしワークショップか展示かどちらとも取れる文章なので

BlocklyDuinoって何？何ができるの？．．．
↓
BlocklyDuinoの展示ブースでは、BlocklyDuinoって何？何ができるの？．．．

というふうに変えたほうがわかりやうしかな？とどうでしょう。

**Comment by kozaru** [comment]
フォントサイズの変更で対応できるなら、私でも可能ですが、下揃えができるかなぁとかさっくりクロームのDeveloperツールで入れてみるとこんな感じでした。（入れるとして、ちょっと先になります。）

![2016-06-16 20 33 30](https://cloud.githubusercontent.com/assets/2457308/16115434/e5d54c58-3401-11e6-8206-a2b05692912c.png)

**Comment by kozaru** [comment]
今から家事タイムなので、入れると決まって、戻った時に対応まだやったら、対応しますね。

**Comment by kozaru** [comment]
`/`は全角`／`ですね。

**Comment by ixkaito** [comment]
@mayurin 
横はスマホの時改行になってしまいますのでちょっと微妙ですね…
スマホの時だけ下かな

@kozaru 
入れるって決まったら対応しますよ。

**Comment by kozaru** [comment]
@ixkaito 助かります。よろしくお願いします！

**Comment by tkc49** [comment]
ふむふむ。なるほどー。
杉山さんが書かれているように展示なのかワークショップなのかが分かれば良いですー！^^
日本語入れることでダサくなってしまう、またはすごく手間なら特に良いかなと思います−！

下の説明文章を書き換えるのもOKですー！
@asaga さんアサインした方が良いのかな。

**Comment by asaga** [comment]
説明文を変える事はできると思います。
が、それぞれの説明文に「○○の展示ブースでは〜」って書くのでは冗長な気もしてて…。

ちなみに、僕もExhibitionはググりましたw

**Comment by pictron** [comment]
Exhibitionはギャラリーなんかでは、良く使いますね。
全部に「○○の展示ブースでは〜」とは書くのではなく、それぞれ少し言葉を補えばいいと思います。

**Comment by pictron** [comment]
例えばこんな感じ

BlocklyDuinoって何？何ができるの？
↓
BlocklyDuinoの展示ブースでは、BlocklyDuinoって何？何ができるの？

何でも相談してください！
↓
イベント開催中に常時相談を受け付けるカウンターを設置します、何でも相談してください！

忍者ブースはそのままで。

パーラービーズ（アイロンビーズ）を通じて．．．
↓
実際に手を動かして作る体験ブース、パーラービーズ（アイロンビーズ）を通じて．．．

MR（Mixed Reality：混合現実）と．．．
↓
人気必至のMixed Realityの体験ブース。MR（Mixed Reality：混合現実）と．．．

**Comment by asaga** [comment]
BlocklyDuino、パーラービーズ、ドローンはタイトルで体験型と分かりそうな気がするんですが、変えた方が良いですかね？
相談カウンターは杉山さんの案で賛成です。

**Comment by asaga** [comment]
ドローンについては説明文が長すぎて削ろうとしているところなので、やはり現状維持でいきたいと思います。
相談カウンターだけ変更する方向でどうでしょうか？

**Comment by pictron** [comment]
ま、私のざっと考えただけなので、浅賀さんのほうで最終決めていただいて。体験と入れたのはワークショップのようにがっつりしたものなのか？体験なのかがわかればと、なくてもなんとなくはわかると思います。

**Comment by asaga** [comment]
@tkc49 
展示関係はタイトル見れば大体判断できそうなので、CoderDojo相談カウンターだけ微修正する方向で進めたいと思います。

何でも相談してください！
↓
イベント開催中、いつでもご相談を受け付けるカウンターを設置します。何でも相談してください！

**Comment by kozaru** [comment]
@tkc49 
@asaga 

> 展示関係はタイトル見れば大体判断できそうなので、CoderDojo相談カウンターだけ微修正する方向で進めたいと思います。
> 
> 何でも相談してください！
> ↓
> イベント開催中、いつでもご相談を受け付けるカウンターを設置します。何でも相談してください！

上記どうしましょうか？修正されますか？

**Comment by asaga** [comment]
@kozaru 修正はお願いしますm(_ _)m

**Comment by kozaru** [comment]
@asaga 修正しました。
このチケットcloseしてよいかよくわからないので、よいようなら、closeしてください。
今回修正以外にも確認事項あるようなら、引き続き、よろしくお願い致します！

**Comment by asaga** [comment]
@tkc49 元々、日本語表記の話しから始まりましたが、現状の内容で確定としますね。
もし、まだ分かりにくいとかあれば言ってください。

**Comment by tkc49** [comment]
@asaga 了解です！
