### ISSUE TITLE
NOW PRINTINGの画像つくりました

### ISSUE THREAD

**Issue by mayurin** [dojocon-japan/dojocon-japan.github.io#93]
https://drive.google.com/folderview?id=0B-O-Ui4qJxjLNzdyNjVhUWx2cjQ&usp=sharing

**Comment by kozaru** [comment]
@mayurin ありがとうございます！
Exhibition用 600 x 360 もほしいです。

**Comment by mayurin** [comment]
@kozaru 入れました！

**Comment by kozaru** [comment]
@mayurin 後ほど差し替えておきまーす！

**Comment by kozaru** [comment]
@mayurin マージしました。Closeします。

**Comment by kozaru** [comment]
@ixkaito NewsのNowPrinting修正しました。
2052549
IssueNo入れ忘れました。すみません。

**Comment by kozaru** [comment]
@mayurin 画像のファイル名を`nowprinting0\-600x400.jpg`の形式に修正しました。
その他の画像と統一するためです。いただいたGoogleドライブ内のファイルも変更済みです。
