### ISSUE TITLE
Speakerの英語表記について

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#97]
@Ippey @tkc49 
高坂さんが、Slackで英語表記についてご連絡くださいました。

> サイト確認しました。私はGitHubのアカウント持ってないのでここでコメントさせてください。トップページの登壇者の紹介部分（写真＆名前）のところで、東さんの英語名だけHIGASHI, Kazukiとファミリーネームが先に来て大文字になっているところが結構気になりました。論文の名前の表記のようなスタイルですよね。ご本人が提供された表記だとは思いますが、できたら他の方と統一してKazuki Higashiとしたほうが見た目に良いと思いました。

上記のように修正してもよいですか？東さんに確認した方がよいですか？その場合、一平さん確認お願いできますか？

**Comment by Ippey** [comment]
修正しましょう。公開後、他とテイストを合わせて旨メールします。

**Comment by kozaru** [comment]
@Ippey 修正しました。Closeします。
