### ISSUE TITLE
Exhibition 写真追加_バーチャルドローン

### ISSUE THREAD

**Issue by kozaru** [dojocon-japan/dojocon-japan.github.io#99]
@akari-doi シートに追加しています。
よろしくお願いいたします。

**Comment by akari-doi** [comment]
@kozaru フォルダへ入れました！よろしくお願いいたします！

**Comment by kozaru** [comment]
https://megumilog.backlog.jp/view/DOJOCON-448より

追記：写真提供のところに『株式会社XOOMS(ズームス）』といれてくださいm(_ _)m

**Comment by akari-doi** [comment]
これはhtmlでキャプションいれていただいているみたいなので私はなにもしなくても大丈夫そうですか？

**Comment by kozaru** [comment]
@akari-doi はい、大丈夫です！
対応ありがとうございました！

**Comment by kozaru** [comment]
追加したのでCloseします。
